### ISSUE TITLE
!!python/object/apply:pymdownx.slugs.slugify is removed from mkdocs.yml

### ISSUE THREAD

**Issue by y-young** [readthedocs/readthedocs.org#10013]
## Details

* Build URL (if applicable): [https://readthedocs.org/projects/nazurin/builds/19446432/](https://readthedocs.org/projects/nazurin/builds/19446432/)

## Expected Result

`mkdocs.yml` retains `!!python/object/apply:pymdownx.slugs.slugify` tag and documentation successfully built

```yaml
markdown_extensions:
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
```

## Actual Result

The tag is removed, causing build to fail:
```yaml
markdown_extensions:
- toc:
    permalink: true
    slugify: null
```

## Note

The configuration is to support TOC slugify for unicode (https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/?h=slugify#unicode)

https://facelessuser.github.io/pymdown-extensions/extras/slugs/
