### ISSUE TITLE
Build failure with a virtualenv error

### ISSUE THREAD

**Issue by Bilokin** [readthedocs/readthedocs.org#10047]
Hello everyone,

I have a build failure with a virtualenv error for a project which uses conda:
```
python -mvirtualenv $READTHEDOCS_VIRTUALENV_PATH
SystemExit: 2
usage: virtualenv [--version] [--with-traceback] [-v | -q] [--read-only-app-data] [--app-data APP_DATA] [--reset-app-data] [--upgrade-embed-wheels] [--discovery {builtin}] [-p py] [--try-first-with py_exe]
                  [--creator {builtin,cpython3-posix,venv}] [--seeder {app-data,pip}] [--no-seed] [--activators comma_sep_list] [--clear] [--no-vcs-ignore] [--system-site-packages] [--symlinks | --copies] [--no-download | --download]
                  [--extra-search-dir d [d ...]] [--pip version] [--setuptools version] [--wheel version] [--no-pip] [--no-setuptools] [--no-wheel] [--no-periodic-update] [--symlink-app-data] [--prompt prompt] [-h]
                  dest
virtualenv: error: the following arguments are required: dest
```

I think this error is related to this recent PR.: https://github.com/readthedocs/readthedocs.org/pull/9971

Is there a problem in my setup? 
Or do I need to set `READTHEDOCS_VIRTUALENV_PATH` environment variable value from now on?

## Details

* Read the Docs project URL:  https://syscorrfw.readthedocs.io/en/latest/

My readthedocs.yaml:
```
---
version: 2
formats: all
conda:
  environment: .environment.yml
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

python:
  install:
    - method: pip
      path: .
```
My environment.yaml:

```
name: rtd38
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
```

Related https://github.com/readthedocs/readthedocs.org/issues/9008

**Comment by ericholscher** [comment]
Thanks for the issue. Can you link to the build where this is happening?

**Comment by jprestop** [comment]
@ericholscher I do not know @Bilokin, but I am having a similar problem, but I am not using conda.  Here is a link to my projects [readthedocs.yaml file](https://github.com/dtcenter/MET/blob/main_v11.0/.readthedocs.yaml) and a link to [one of the builds](https://readthedocs.org/projects/met/builds/19548026/) where this is happening.  Here is a link to a previously [successful build](https://readthedocs.org/projects/met/builds/19547765/).  Any guidance you can give would be much appreciated.

**Comment by Bilokin** [comment]
@ericholscher , sure: https://readthedocs.org/projects/syscorrfw/builds/19539247/

**Comment by humitos** [comment]
When using Conda, you should specify conda in the `build.tools.python` config:

```yaml
build:
  os: ubuntu-22.04
  tools:
    python: "miniconda3-4.7"  # or, ideally, "mambaforge-4.10"
```

Can you try updating your config file and building again?
