### ISSUE TITLE
Config: Add explicit options to exclude a project from search

### ISSUE THREAD

**Issue by benjaoming** [readthedocs/readthedocs.org#10092]
Some documentation projects want to have their own search in place of server side search. This means that none of the search features should be active on the project. Some projects can want a mix of this.

This might be a bit complicated, but there are several cases to cover for:

* a) Project wants to disable in-doc searching (but keep the project indexed so it appears in Dashboard searches and global searches)
* b) Project wants to exclude itself from dashboard searches (but keep in-doc search and global search)
* c) Project wants to exclude itself from global searches (but keep in-doc search and dashboard search) (only valid for community projects)
* d) Project wants to disable in-doc search and excluded from global search and dashboard search

Only d) would benefit from disabling indexing, but it's not necessary given that there are explicit options for in-doc, dashboard and global search inclusion.

Currently, we can remove all pages from search indexing: `search.ignore: all` is perhaps better than `search.ignore: '*'`.. but it doesn't really matter, since this does not work for a), b) nor c).

Here's a rough sketch of how that could look:

```
search:
   include: # unchanged
   exclude: all # new option 'all' in place of '*'
   scopes:
       indoc: disable  # default: enable. The meaning of 'disable' is also to remove extensions to the documentation tool, Sphinx or MkDocs.
       global: disable  # default: enable
       dashboard: disable  # default: enable
```
