### ISSUE TITLE
Cannot create virtualenv, $READTHEDOCS_VIRTUALENV_PATH appears to be empty

### ISSUE THREAD

**Issue by EricR86** [readthedocs/readthedocs.org#10207]
## Details

* Read the Docs project URL: [https://readthedocs.org/projects/segtools/](https://readthedocs.org/projects/segtools/)
* Build URL (if applicable): [https://readthedocs.org/projects/segtools/builds/19897082/](https://readthedocs.org/projects/segtools/builds/19897082/)
* Read the Docs username (if applicable): [https://readthedocs.org/projects/segtools/](https://readthedocs.org/profiles/ericr86/)

## Expected Result

The build to continue, and in this case the virtual environment to be created. I'm willing to concede that I might be configuring things wrong so I've attached my yaml file below. Namely my python project needs to be installed for the docs to generate. To do so I need a conda environment and to be able to run a command (a make with a specific rule) post-install to generate additional text included in the .rst files.

## Actual Result

On the command: `python -mvirtualenv $READTHEDOCS_VIRTUALENV_PATH`
The following error is produced: `virtualenv: error: the following arguments are required: dest`

.readthedocs.yaml reference:
```
version: 2

conda:
  environment: environment.yml

# Required for project building and versioning
python:
   install:
      - method: pip
        path: .

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  jobs:
    post_install:
      - make -C doc cmdline-help

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: doc/conf.py
```

Thanks for your time and consideration.
