### ISSUE TITLE
I don't manage to install jupyter in RDT build

### ISSUE THREAD

**Issue by 12rambau** [readthedocs/readthedocs.org#10223]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/ipyvuetify
* Build URL (if applicable): https://readthedocs.org/projects/ipyvuetify/builds/20010475/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/borntobealive/

## Expected Result

I would like to improve the documentation of the ipyvuetify lib and specifically build the API documentation. To do so I need to generate the widgets as there are not included in the files but generated upon installation. I need to install jupyter before installing the ipyvuetify lib to trigger the installation process.

```yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# build with latest available ubuntu version
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
    nodejs: "14"
  jobs:
    pre_install:
      - python -m pip install jupyter

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
```

## Actual Result

It works fine on my local computer but in RDT I repeatidly face the same issue (in https://github.com/widgetti/ipyvuetify/pull/240). 

```
Traceback (most recent call last):
        File "/home/docs/checkouts/readthedocs.org/user_builds/ipyvuetify/envs/240/bin/jupyter", line 5, in <module>
          from jupyter_core.command import main
      ModuleNotFoundError: No module named 'jupyter_core'
```

looking on the web this package is included in `jupyter` that (as shown in previous file) is pre-installed. 

do you have any idea why the lib is missing ?
