### ISSUE TITLE
clarification: .readthedocs.yaml, conf.py and requirements.txt

### ISSUE THREAD

**Issue by jaygray0919** [readthedocs/readthedocs.org#10264]
We build our documents on https://readthedocs.org/ using the `sphinx-rtd-theme`

We want to use `.readthedocs.yaml` but are a bit confused about the **inter-relationship** among `.readthedocs.yaml`, `conf.py` and `requirements.txt`

For example, in **base-0** (no YAML file), we declare these extensions in `conf.py`:

```
extensions = [
    'sphinxcontrib.bibtex',
    'sphinx.ext.graphviz',
    ]
```

Our `requirements.txt` looks like this:

```
sphinx-rtd-theme
sphinxcontrib-bibtex
```

We do not add `sphinx-ext-graphviz` to `requirements.txt`.
The build works as expected - all is good.

Next, we experiment with `.readthedocs.yaml` (**base-1**).
We did not change the **base-0** configuration.
Our `.readthedocs.yaml` looks like this:

```
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

sphinx:
   configuration: docs/conf.py

python:
   install:
   - requirements: docs/requirements.txt
```

**base-1** build was successful but our `graphviz` diagrams failed (only graphviz source code is displayed in html).

Do we declare the `sphinx.ext.graphviz` in `.readthedocs.yaml`?

Or, do we declare all extensions initialized by `conf.py` in `requirements.txt`, like this:

```
sphinx-rtd-theme==1.1.1
sphinxcontrib-bibtex==2.5.1a0
sphinx-ext-graphviz==0.6
```

Asked another way ...

Is the above YAML file correct when using most sphinx extensions? Do we dupicate the extension declarations in `conf.py` and `requirements.txt`; specifying the version for the target extension in `requirements.txt`?

We plan to use the mermaid extension and see that we need to update `.readthedocs.yaml` like this:

```
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
    nodejs: "16"
  jobs:
      post_install:
        - npm install -g @mermaid-js/mermaid-cli
```

Presumably, we then initialize `sphinxcontrib.mermaid` for `conf.py` and add `sphinxcontrib-mermaid==0.8.1` to `requirements.txt`.

But our main issue is learning the correct configuration/segmentation for these three documents:
  +  `.readthedocs.yaml`, `conf.py` and `requirements.txt`

Help and guidance is appreciated.
