### ISSUE TITLE
Could not import extension sphinx.builders.linkcheck (exception: urllib3 v2.0 only supports OpenSSL 1.1.1+)

### ISSUE THREAD

**Issue by stereoshoots** [readthedocs/readthedocs.org#10290]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/gitlab-board
* Build URL (if applicable): https://readthedocs.org/projects/gitlab-board/builds/20387388/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/stereoshoots/

## Expected Result

New revision of docs should be builded.

## Actual Result

Error is thrown:

```
Could not import extension sphinx.builders.linkcheck (exception: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2n  7 Dec 2017. See: https://github.com/urllib3/urllib3/issues/2168)
```

Is this a problem on my side? It installs pip packages in build, how should i fix this?

**Comment by agjohnson** [comment]
More specifically, to use a configuration file, you should use a configuration file that that specifies the build OS:

```yaml
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
```

This will ensure you are not using one of the older images.

**Comment by agjohnson** [comment]
@sethmlarson Thanks for the note, I'd agree the configuration fix should be the recommended fix. I'll edit the guidance above.

It seems like we're probably going to aim to get some sort of fix out here, as this is causing a bit of trouble for folks. It seems the trouble is an old pyenv compiled Python in an image we're trying to deprecate, but should be something we can fix.

Unfortunately, we're going into Write the Docs conference time, so we haven't settled on a timeframe yet.

**Comment by agjohnson** [comment]
Also, I opened an issue yesterday for updating and fixing the legacy build image:
https://github.com/readthedocs/readthedocs-docker-images/issues/194

We'll track updating and fixing the image there. I'll see what I can do today and tomorrow

**Comment by mmmarinho** [comment]
If another poor soul is here from using the [readthedocs template](https://github.com/readthedocs/tutorial-template), here's what worked for me.

Add the `.readthedocs.yaml` at the root of your repo. Note the `docs/source/conf.py`, which can be easily overlooked from the [config file example](https://docs.readthedocs.io/en/stable/config-file/v2.html).

``` yaml
# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    # You can also specify other tool versions:
    # nodejs: "19"
    # rust: "1.64"
    # golang: "1.19"

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/source/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
#    - pdf

# Optionally declare the Python requirements required to build your docs
# python:
#  install:
#   - requirements: docs/requirements.txt
```
