### ISSUE TITLE
'jQuery is not defined' when using .readthedocs.yaml

### ISSUE THREAD

**Issue by Dramelac** [readthedocs/readthedocs.org#10318]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/exegol/  | https://exegol.readthedocs.io/en/jsbug/
* Build URL (if applicable): https://readthedocs.org/projects/exegol/builds/20624368/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/Dramelac/

We didn't have any problem with or previous setup without a `.readthedocs.yaml` (as you can see in our `latest` version of the documentation. 
For test & debug purpose i created a `jsbug` branch / version to showcase the bug: https://exegol.readthedocs.io/en/jsbug/

Am I missing something with the configuration ?

The config file:
```yml
# .readthedocs.yaml

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: source/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
formats: all

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - requirements: requirements.txt
```

## Expected Result

- The user should be able to open the side bar from the movile view
- The user should be able to open the readthedocs 'popup' ? on the bottom left of the page to select a version, a branch or download the doc in another format

## Actual Result

- Clicking on the 'hamburger' button on the mobile view doesn't open the menu
- Clicking on the readthedocks overlay doesn't open the section to navigation between version & formats etc
- An error message regarding jQuery is raised in the console:
![image](https://github.com/readthedocs/readthedocs.org/assets/10145128/a5214745-eb63-4fe3-9c07-60eeeb46e619)

Thank you for the help !
