### ISSUE TITLE
Build: support Ruby under `build.tools` 

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#10346]
We should add support for Ruby on `build.tools`. It will be useful for doctools like Jekyll.

Work required:

- [x] Update the documentation
- [x] Install asdf-ruby (https://github.com/asdf-vm/asdf-ruby) on Docker images
- [ ] Compile latest Ruby version and upload it S3
- [x] Update `settings.py` to add this tool and version
- [x] Update config v2 to accept this value
- [x] Create a branch on `test-builds` for this use case

> **Note**: we had a support request for this at https://github.com/readthedocs/readthedocs.org/issues/9599#issuecomment-1560011462

**Comment by humitos** [comment]
I note there are other people installing Julia as well in a pretty weird form. We should probably document how to install _any tool supported by `asdf`_ in an easy way. The process is like:

```yaml
build:
  commands:
    - asdf plugin add <tool> <asdf plugin url>
    - asdf install <tool> <version>
    - asdf global <tool> <version>
```

Users should be able to do this _without_ our intervention. However, for those tools that require to be compiled or are heavy in network transfer, we should probably include them in our S3 cache.

**Comment by henryiii** [comment]
FYI, this (storing in S3) would save 379s. 89s to compile the required modules for Jekyll would remain. I’d be fine with only a recent (3.2 or 3.1 ruby) cached.

**Comment by Jasha10** [comment]
Note to future travelers:
using the `build.command` key as demonstrated in the [comment above](https://github.com/readthedocs/readthedocs.org/issues/10346#issuecomment-1576570469) will result in readthedocs' pre-defined process being entirely overridden.

If you just want to extend the build with additional steps, the following may be more appropriate:
```yaml
build:
  jobs:
    post_system_dependencies
      - asdf plugin add <tool> <asdf plugin url>
      - asdf install <tool> <version>
      - asdf global <tool> <version>
```

**Comment by humitos** [comment]
I added support for Ruby 3.3.x in our build images. I tested it locally and it worked fine. This work will be deployed next Tuesday, and I'd love to heard some feedback from people already using "the hacky way" 🙏🏼 

Now, Ruby is available under the normal `build.tools` configuration option:

```yaml
build:
  tools:
    ruby: "3.3"
```

This will use a pre-compiled version of Ruby, making the builds to build faster.
