### ISSUE TITLE
build.apt_packages: installing the 'time' package does not work

### ISSUE THREAD

**Issue by woutdenolf** [readthedocs/readthedocs.org#10359]
## Details

I have a project that needs the "time" command during build. However adding it to build.apt_packages does not seem to work:

```yaml
version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - time
  tools:
    python: "3.10"
  commands:
    - command time -p ls
```

## Expected Result

```
command time -p ls

real 0.00
user 0.00
sys 0.00
```

## Actual Result

```
command time -p ls

/bin/sh: 1: time: not found
```

## Temporary fix

Build the time package from source

```yaml
version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - build-essential
  tools:
    python: "3.10"
  commands:
    - curl http://ftp.gnu.org/gnu/time/time-1.9.tar.gz > time-1.9.tar.gz
    - tar -zxvf time-1.9.tar.gz
    - ( cd time-1.9 && ./configure --prefix=$HOME/.asdf && make && make install )
    - command time -p ls
```
