### ISSUE TITLE
Build fails for `sphinx=6.2.1`, claiming "requires docutils >=0.18.1,<0.20, but none of the providers can be installed"

### ISSUE THREAD

**Issue by michaelweinold** [readthedocs/readthedocs.org#10477]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/brightway-documentation/
* Build URL (if applicable): https://readthedocs.org/projects/brightway-documentation/builds/21130710/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/michaelweinold/

## Expected Result

No issues - if I create the environment locally using `conda env create -f environment.yml`, I don't get any errors either. My environment file:

```yaml
name: sphinx
channels:
  - conda-forge
  - nodefaults
dependencies:
  # core functionality
  - python=3.11
  - ipython
  # sphinx
  - sphinx=6.2.1 # sphinx-design currently requires sphinx[version>=2,<5] # https://github.com/sphinx-doc/sphinx/releases
  # theme and extensions
  - pydata-sphinx-theme=0.13.3 # website theme # https://github.com/pydata/pydata-sphinx-theme/releases
  - myst-parser=2.0.0 # Markdown support # https://github.com/executablebooks/MyST-Parser/releases
  - nbsphinx=0.9.2 # Jupyter notebook support # https://github.com/spatialaudio/nbsphinx/releases
  - sphinx-autoapi=2.1.0 # to build docs from source code instead of package import # https://github.com/readthedocs/sphinx-autoapi/tags
  - sphinx-design=0.4.1 # responsive web component support # https://github.com/executablebooks/sphinx-design/releases
  - sphinx-notfound-page=0.8.3 # custom 404 page # https://github.com/readthedocs/sphinx-notfound-page/tags
  - graphviz=8.0.5 # for plotting dependency diagrams with sphinx-autoapi # https://anaconda.org/conda-forge/graphviz/files
  - sphinx-favicon=1.0.1 # for custom favicons # https://github.com/tcmetzger/sphinx-favicon/releases
  - sphinx-copybutton=0.5.2 # for copy button in code blocks # https://github.com/executablebooks/sphinx-copybutton/releases
  # build process
  - sphinx-autobuild=2021.3.14 # live-html support # https://github.com/executablebooks/sphinx-autobuild/releases
```

## Actual Result

```
mamba env create --quiet --name latest --file environment.yml
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
Encountered problems while solving:
  - package sphinx-6.2.1-pyhd8ed1ab_0 requires docutils >=0.18.1,<0.20, but none of the providers can be installed
```
