### ISSUE TITLE
The virtual environment does not have the system packages as expected

### ISSUE THREAD

**Issue by jnikula** [readthedocs/readthedocs.org#10500]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/hawkmoth/
* Build URL (if applicable): https://readthedocs.org/projects/hawkmoth/builds/21154435/

## Expected Result

I'm installing `python3-clang` using `apt`, enabling `python.system_packages`, and expect my Sphinx extension to be able to import the package.

```
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - python3-clang

python:
  install:
    - method: pip
      path: .
  system_packages: true
```

The build log shows the system package was installed, and `--system-site-packages` was passed to the virtual environment.

## Actual Result

Import fails with `ModuleNotFoundError: No module named 'clang'`.
