### ISSUE TITLE
List styling is broken in RTD build - <ul><li> items don't show bullets and have no indentation - local build works

### ISSUE THREAD

**Issue by vsajip** [readthedocs/readthedocs.org#10556]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/gnupg/
* Build URL (if applicable): https://readthedocs.org/projects/gnupg/builds/21367346/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/vsajip/

## Expected Result

As per this example of an unordered list:

![ss32](https://github.com/readthedocs/readthedocs.org/assets/130553/02bfc8dc-2ab6-4045-88c3-c249df64ca15)

The above is what I get when built locally using the latest `sphinx_rtd_theme` from PyPI.

## Actual Result

![ss15](https://github.com/readthedocs/readthedocs.org/assets/130553/b41c8fc5-6e20-41b6-8c3c-47806bdcdcc1)

The above is what I get on [RTD](https://gnupg.readthedocs.io/en/latest/#custom-handling-of-data-streams).

If I look at the CSS from RTD for the list and list items, I see these rules applying:

```css
ul, ol, dl {
  margin: 0;
  padding: 0;
  list-style: none;
    list-style-image: none;
  list-style-image: none;
}

li {
  list-style: none;
}
```
On the local build, I see:
```css
.rst-content .section ul, .rst-content .toctree-wrapper ul,
.rst-content section ul, .wy-plain-list-disc, article ul {
	list-style: disc;
	line-height: 24px;
	margin-bottom: 24px;
}
 
.rst-content .section ul li, .rst-content .toctree-wrapper ul li,
.rst-content section ul li, .wy-plain-list-disc li, article ul li {
	list-style: disc;
	margin-left: 24px;
}
```
Clearly, the CSS rules on RTD seem wrong.
