### ISSUE TITLE
Add support for additional pip CLI options in .readthedocs.yaml

### ISSUE THREAD

**Issue by Mr0grog** [readthedocs/readthedocs.org#10789]
## What's the problem this feature will solve?

I have a project with some complex binary inter-dependencies, and which normally needs to be installed using the `--no-binary` option:

```sh
pip install . --no-binary lxml
```

Right now, it doesn’t seem like there’s a way to specify that in the `.readthedocs.yaml` file. I’m currently working around it by using a `requirements` style install, since `requirements.txt` files can have this pip option in them.

## Describe the solution you'd like

I’d love to see a new key added to the ability to add extra CLI options to pip installations via a `cli_options` or similar key in `python.install.*`:

```yaml
python:
  install:
    - method: pip
      path: "."
      cli_options:
        - '--no binary'
        - 'lxml'
```

I suppose this could also be a string (instead of a list of arguments), or some other format. It doesn’t need to look exactly like above. (There could also be narrower support for just the `--no-binary <dependency_name>`  option as a special key, rather than the more general "additional CLI options" idea I’m proposing here.)

## Alternative solutions

I can work around this for now by having a `requirements.txt` file with the dependencies that need to be built together. In my particular case, that’s `lxml` and `html5-parser`, so I have:

In `requirements.txt`:
```
html5-parser >=0.4.0,<0.5 --no-binary lxml
lxml >=4.5.0,<5
```

And in `.readthedocs.yaml`:

```yaml
python:
  install:
    # Install requirements.txt first to make sure the --no-binary option is used for html5-parser/lxml.
    - requirements: "requirements.txt"
    # Then actually install the package.
    - method: pip
      path: "."
```

It’s just not nearly as nice. :)
