### ISSUE TITLE
Paths must be resolved using config directory

### ISSUE THREAD

**Issue by mvorisek** [readthedocs/readthedocs.org#10806]
## Details

custom config:

```
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: '3.11'

python:
  install:
    - requirements: requirements.txt
```

saved in docs/.readthedocs.yaml`

and configured in admin:

![image](https://github.com/readthedocs/readthedocs.org/assets/2228672/5ff9bfc3-f7a5-43df-b254-eac8e499c51b)

## Expected Result

`python.install.requirements: requirements.txt` must be resolved to `docs/requirements.txt` instead of `requirements.txt`

## Actual Result

![image](https://github.com/readthedocs/readthedocs.org/assets/2228672/d1513dfd-261c-4ba8-8c83-fcf4794e5303)
