### ISSUE TITLE
PDFs Not Generating in ReadTheDocs Flyer Menu 

### ISSUE THREAD

**Issue by sachin-suresh-rapyuta** [readthedocs/readthedocs.org#10861]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/io-amr-rr-pa-amr/
* Build URL (if applicable): https://readthedocs.com/projects/io-amr-rr-pa-amr/builds/1797543/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/{your_rtd_username}/

## Expected Result

 After enabling the "Enable PDF build" checkbox in my Advanced Settings, PDFs are not being generated in the ReadTheDocs flyer menu.

Here is my `.readthedocs.yml` file which includes commands to build PDF from [simple-pdf extension](https://sphinx-simplepdf.readthedocs.io/en/latest/). Although the build succeeds executing all the commands, I cant see the PDF in flyer menu.

```
# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

#submodules:
#  include:
#    - paamr-deployment

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
    # You can also specify other tool versions:
    # nodejs: "16"
    # rust: "1.55"
    # golang: "1.17"
  #Add custom simple-pdf to readthedocs flyer menu
  commands:
    - pip install -r docs/requirements.txt
    - sphinx-build -b simplepdf docs .
    - mkdir -p _readthedocs/html/
    - sphinx-build -b html docs _readthedocs/html

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
formats: all

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - requirements: docs/requirements.txt

```

## Actual Result

Just like HTML, even PDFs (including custom) should be build on every PR build.
