### ISSUE TITLE
Allow `latest` versions of conda/mamba/ in `.readthedocs.yml`

### ISSUE THREAD

**Issue by tdegeus** [readthedocs/readthedocs.org#10912]
## What's the problem this feature will solve?

Often one does not care on which version the documentation is build. It would be good if one could accept a default `latest` version.

## Describe the solution you'd like

```yaml
version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-latest
  tools:
    python: mambaforge-latest

conda:
  environment: environment.yaml
```

## Alternative solutions

An alternative would be to have a bot open PRs on the source's repository if a version changes. Currently a lot of people have to do a lot of manual work for something that they likely don't care about

## Additional context

-
