### ISSUE TITLE
Build error with build id #23022567

### ISSUE THREAD

**Issue by zaneselvans** [readthedocs/readthedocs.org#10999]
## Details:

* Project URL: https://readthedocs.org/projects/catalystcoop-pudl/
* Build URL(if applicable): https://readthedocs.org/projects/catalystcoop-pudl/builds/23022567/
* Read the Docs username(if applicable): zaneselvans

## Expected Result

Expected the documentation associated with a pull request to be built.

## Actual Result

The documentation build failed, and a warning about not having a `.readthedocs.yaml` configuration file was displayed, but we **do** have a `.readthedocs.yaml` config in the repo.  Is there something wrong with it? Or is there additional configuration that needs to be migrated into it?

Current contents of our `.readthedocs.yaml`:

```yaml
---
# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-22.9

# Define the python environment using conda / mamba
conda:
  environment: environments/conda-linux-64.lock.yml

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: true

# Set the version of Python and requirements required to build your docs
python:
  install:
    - method: pip
      path: .
```
