### ISSUE TITLE
Search ranking seemingly has no effect

### ISSUE THREAD

**Issue by astrojuanlu** [readthedocs/readthedocs.org#11060]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/kedro/

## Expected Result

In https://github.com/kedro-org/kedro/pull/3546 we added this to .readthedocs.yml:

```yaml
search:
  ranking:
    # Match API docs (files prefixed "kedro.") and push them down the ranking
    '*/kedro.*.html': -5
```

with the intention of having narrative docs show above API pages for search. 

## Actual Result

We still see API results on top.

See for example searching for "node":

<img width="766" alt="image" src="https://github.com/readthedocs/readthedocs.org/assets/316517/57647682-1d36-49a7-90ca-d7beb6162c8a">

in https://docs.kedro.org/en/latest/

- Should we have marked this as -10 to drop it right down?
- Should we also boost the narrative docs up?
- Should we even expect to see results right now, or is the indexing done separately to the HTML build? How can I force a new index?

cc @stichbury
