### ISSUE TITLE
Npm install support

### ISSUE THREAD

**Issue by LecrisUT** [readthedocs/readthedocs.org#11216]
## What's the problem this feature will solve?

Similar to the `python.install` feature, it would be nice to support a `npm.install` as well. Maybe also `cargo` and `go`?

## Describe the solution you'd like

A small wrapper for `npm install` (and `npm build`?) to automatically build the packages in `package.json`. Having first-party support would be helpful, because than the caching can be more efficiently shared.

## Alternative solutions

Manual control of `cache` artifacts

**Comment by agjohnson** [comment]
We were sort of discussing this recently. Right now, our default commands executed for builds are meant to serve Python based projects. This comes from all of the tooling we directly supported historically being Python based tools -- Sphinx and Mkdocs.

More direct support for Node/etc tooling is getting into some new area for us, so we don't yet have concrete plans here. Feedback here is definitely helpful for us!

So, a few things that we've discussed at some points:

We've talked about at very least offering overrides to default build jobs. These are discussed more here:

- [Extending the build process](https://docs.readthedocs.io/en/stable/build-customization.html#extend-the-build-process)

The missing jobs right now are:

- `build.jobs.install` - Override all of our install commands
- `build.jobs.build.html` - Override all of our (HTML) build commands

You can sort of accomplish this now with the `pre_install`/`post_install` jobs too. But official support might look like:

```yaml
build:
  jobs:
    install:
      - npm install
    build:
      html:
        - npm run build
        - ...
```

As far as native support for npm install in our configuration file, these additions are hard for us to maintain. So, we might instead prefer to keep npm/etc support at simply overriding `build.jobs.install` for now. This feels reasonable as there probably isn't much to gain from our configuration file acting as a proxy.

You can also do this with `build.commands` but need to control the build process entirely.

Our eventual goal here is to support/offer reusable, community build packages, where users only need to specify the tooling package and it's arguments. This is a far ways out though.

As far as caching goes, we do not cache anything between builds anyways. Each build requires a full, fresh checkout of your repository. We've tried caching layers and surprisingly saw little improvement with build time.

**Comment by humitos** [comment]
We deployed a feature that allows to build using `build.jobs.install` and `build.jobs.build.html` without specifying `sphinx` nor `mkdocs` keys. Example to build a Docusaurus site:

```yaml
version: 2

build:
  os: ubuntu-24.04
  tools:
    nodejs: "22"
  jobs:
    install:
      # Install all dependencies for the site
      - cd docs/ && npm install
    build:
      html:
        # Build the site
        - cd docs/ && npm run build
    post_build:
      # Copy generated files into Read the Docs directory
      - mkdir --parents $READTHEDOCS_OUTPUT/html/
      - cp --recursive docs/build/* $READTHEDOCS_OUTPUT/html/
```

With this implementation users are now able to override `build.jobs.*` without the need of using `build.commands` 🎉 . Let us know if you find this useful for your use case.
