### ISSUE TITLE
Incident: RTD builder stuck

### ISSUE THREAD

**Issue by LecrisUT** [readthedocs/readthedocs.org#11217]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/mystmd-temp/
* Build URL: https://readthedocs.org/projects/mystmd-temp/builds/23750011/

This is a custom build with:
```yaml
version: 2
build:
  os: ubuntu-22.04
  tools:
    nodejs: "20"
  commands:
    - npm install
    - npm run build
    - npm run dev
    - cd docs
    - myst build --html
    - cp -r _build/html $READTHEDOCS_OUTPUT/html
```

Specifically on a PR testing the builder: https://github.com/LecrisUT/mystmd/pull/1

## Expected Result

Update the build log with the current status

## Actual Result

The log is stuck at `npm run build` (or just after finishing that)
