### ISSUE TITLE
Multi-project yaml syntax

### ISSUE THREAD

**Issue by LecrisUT** [readthedocs/readthedocs.org#11238]
## What's the problem this feature will solve?

I was looking at [sphinx-themes.org](https://github.com/sphinx-themes/sphinx-themes.org) and was considering if the build system can be simplified and automated with RTD. If the sub-projects can be managed by the yaml, I think that is indeed doable.

This could help in other project situations where the documentation is sphinx based, but there are other systems for the main website or components, e.g. a static html page or a myst article.

## Describe the solution you'd like

Expand the yaml syntax to allow for a `project` dictionary, where all of the inner components have the same json schema (minus `version`, etc.) as the current schema.
```yaml
version: 2
project:
  /:
    sphinx:
      configuration: docs/conf.py
  /themeA:
    sphinx:
      configuration: docs/themeA/conf.py
```

If the yaml file contains `project`, than the UI interface should be grayed out unless requested to `override`, at which point only the `project./` or top-level schema is read

Adding/Deleting subprojects would be tricky in such cases though, but any automation that the user would create would probably be worse.

## Alternative solutions

Expose the specific sub-project build through a GH action interface. [Relevant issue](https://github.com/readthedocs/actions/issues/27)
