### ISSUE TITLE
warnings.warn(f"tag {tag!r} no version found")

### ISSUE THREAD

**Issue by uliw** [readthedocs/readthedocs.org#11310]
## Details

* https://readthedocs.org/projects/esbmtk/
* https://readthedocs.org/projects/esbmtk/builds/24249513/

## Expected Result
`python -m pip install --exists-action=w --no-cache-dir -r docs/requirements.txt` works locally as expected, and I would expect that this would also work on https://readthedocs.org/ 

## Actual Result

The above command fails with 
```
warnings.warn(f"tag {tag!r} no version found"
...
...
assert version is not None
```

This used to work last fall; for context, I have the following in `.readthedocs.yaml`
```
 jobs:
    pre_build:
      - python -m sphinx -b linkcheck -D linkcheck_timeout=1 docs/ $READTHEDOCS_OUTPUT/linkcheck
    post_checkout:
      - git fetch --unshallow || true
      - git fetch --tags
      
python:
  install:
    - requirements: docs/requirements.txt
    - {path: ., method: pip}
```

I saw a couple of issue posts around the use of git-tags for versioning, but I am none the wiser. Any pointers on how to go about this are much appreciated
