### ISSUE TITLE
'exit 183' is not cancelling the build

### ISSUE THREAD

**Issue by Gabriel-p** [readthedocs/readthedocs.org#11353]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/asteca/
* Build URL (if applicable): https://readthedocs.org/projects/asteca/builds/24475781/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/{your_rtd_username}/

## Expected Result

I'm using the code shown here https://docs.readthedocs.io/en/stable/build-customization.html#cancel-build-based-on-a-condition to cancel builds when the `/docs` folder of my `develop` branch is not changed. Here's my `.readthedocs.yaml`:

```
# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    # You can also specify other tool versions:
    # nodejs: "20"
    # rust: "1.70"
    # golang: "1.20"
  jobs:
    post_checkout:
      # Cancel building pull requests when there aren't changes in the docs directory or YAML file.
      # You can add any other files or directories that you'd like here as well,
      # like your docs requirements file, or other files that will change your docs build.
      #
      # If there are no changes (git diff exits with 0) we force the command to return with 183.
      # This is a special exit code on Read the Docs that will cancel the build immediately.
      - |
        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/develop -- docs/ .readthedocs.yaml;
        then
          exit 183;
        fi

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py
  # You can configure Sphinx to use a different builder, for instance use the dirhtml builder for simpler URLs
  # builder: "dirhtml"
  # Fail on all warnings to avoid broken references
  # fail_on_warning: true

# Optionally build your docs in additional formats such as PDF and ePub
# formats:
#   - pdf
#   - epub

# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
    - requirements: docs/requirements.txt
```

## Actual Result

The build does not halt when I modify files outside of the `/docs` folder, as shown in the build https://readthedocs.org/projects/asteca/builds/24475781/ triggered by [this commit](https://github.com/asteca/ASteCA/commit/a691d3139a5bac5771d13dffb00859173407583b)
