### ISSUE TITLE
Add support for Lua under `build.tools`

### ISSUE THREAD

**Issue by Freed-Wu** [readthedocs/readthedocs.org#11844]
## What's the problem this feature will solve?

Some document use ldoc to build and it needs a lua

## Describe the solution you'd like

build.tools can use lua

## Alternative solutions

Use hererocks.

**Comment by humitos** [comment]
Hi @Freed-Wu! Do you have an example of a project building with `ldoc`?

You can use `asdf` to install Lua in the builder, with something like the following:

```yaml
version: 2

build:
  os: ubuntu-latest
  jobs:
    pre_install:
      - asdf plugin-add lua https://github.com/Stratus3D/asdf-lua.git
      - asdf install lua latest
      - asdf global lua latest
    install:
      # Install ldoc
    build:
      html:
        # Run the commands required to build the project's documentation
```

Let me know if that works.
