### ISSUE TITLE
Pull request preview build fails with Sphinx and `build.commands`, but should succeed

### ISSUE THREAD

**Issue by stevepiercy** [readthedocs/readthedocs.org#11912]
When using Sphinx and `build.commands` in my `.readthedocs.yaml`, according to the blog post [Deprecation of projects using Sphinx or MkDocs without an explicit configuration file](https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/):

> If you are using the `build.commands` feature, you don't need to make any changes, as the `sphinx` and `mkdocs` options are not required when using `build.commands`.

However I get a build error for pull request previews.

---

### Error

The `sphinx.configuration` key is missing. This key is now required, see our [blog post](https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/) for more information.

---

## Details

* Read the Docs project URL: https://readthedocs.org/projects/plone6/
* Build URL (if applicable): https://readthedocs.org/projects/plone6/builds/26826775/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/stevepiercy/

## Expected Result

Pull request builds successfully without making changes to `.readthedocs.yaml`.

## Actual Result

See error message above.

**Comment by humitos** [comment]
Thanks for reporting this. It may be a bug with the latest code we deployed for the deprecation as you realized. @stsewd can you take a look at this?

**Comment by ReenigneArcher** [comment]
I have the same issue with the following config (not using sphinx or mkdocs).

```yml
---
# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "miniconda-latest"
  commands:
    - |
      if [ -f readthedocs_build.sh ]; then
        doxyconfig_dir="."
      else
        doxyconfig_dir="./third-party/doxyconfig"
      fi
      chmod +x "${doxyconfig_dir}/readthedocs_build.sh"
      export DOXYCONFIG_DIR="${doxyconfig_dir}"
      "${doxyconfig_dir}/readthedocs_build.sh"

# using conda, we can get newer doxygen and graphviz than ubuntu provide
# https://github.com/readthedocs/readthedocs.org/issues/8151#issuecomment-890359661
conda:
  environment: third-party/doxyconfig/environment.yml

submodules:
  include: all
  recursive: true
```
