### ISSUE TITLE
mamba>2 installed in `base` environment BUT not used for creating the RTD build environment

### ISSUE THREAD

**Issue by valeriupredoi** [readthedocs/readthedocs.org#12042]
Hi folks, this is somewhat related to https://github.com/readthedocs/readthedocs.org/issues/11690 - we are trying to find a solution whereby `mamba>2` is installed in the RTD `base` conda env, and used to build the Python environment for the RTD build (`mamba<2` can not solve our hefty environment), so I did a bit of config gymnastics and managed to install `mamba==2.0.5` in the base env. Problem is, this mamba is not used to solve the env, so our env still fails to solve, please help, when you have a minute. Very many thanks in advance! Cheers 🍻 

Build https://readthedocs.org/projects/esmvaltool/builds/27454536/
`.readthedocs.yml` file:

```yaml
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-lts-latest
  tools:
    # try miniforge3 when available? see github.com/ESMValGroup/ESMValTool/issues/3779
    # DO NOT use mambaforge-*; that is currently sunsetted
    python: "miniconda-latest"
  jobs:
    pre_create_environment:
      # install mamba2: essential since mamba2 is the only one that can solve the env
      - conda update --yes --quiet --name=base conda
      - conda install --yes --name=base -c conda-forge "mamba>2"
    post_checkout:
      # The ESMValTool repository is shallow i.e., has a .git/shallow,
      # therefore complete the repository with a full history in order
      # to allow setuptools-scm to correctly auto-discover the version.
      - git fetch --unshallow
      - git fetch --all
    pre_install:
      - git stash
    post_install:
      - git stash pop

# Declare the requirements required to build your docs
conda:
  environment:
    environment.yml

# Build documentation in the doc directory with Sphinx
sphinx:
  configuration: doc/sphinx/source/conf.py
  fail_on_warning: true

python:
  install:
    - method: pip
      path: .

# If using Sphinx, optionally build your docs in additional formats such as PDF
formats:
  - pdf
```
