### ISSUE TITLE
Missing Fortran compiler when building online documentation

### ISSUE THREAD

**Issue by wasjabloch** [readthedocs/readthedocs.org#12109]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/relmt/
* Build URL (if applicable): https://app.readthedocs.org/api/v2/build/27860709.txt
* Read the Docs username (if applicable): https://readthedocs.org/profiles/wasjabloch

## Expected Result

Have an online "read the docs" documentation of my project

## Actual Result

Building the documentation fails because of a missing `fortran` compiler

I attempted to mock the Fortran module by including to my `conf.py`:

```
autodoc_mock_imports = ["mccore", "scikit-build-core", "numpy", "scipy"]
```

However, this does not resolve the issue.

**Comment by wasjabloch** [comment]
Missing dependencies can be easily installed following the online documentation:

https://docs.readthedocs.com/platform/stable/config-file/v2.html#build-apt-packages

In my case the following, `.readthedocs.yaml` solved the issue:

```
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - gfortran
    - libfftw3-dev
sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
```
