### ISSUE TITLE
Support `text` format

### ISSUE THREAD

**Issue by barseghyanartur** [readthedocs/readthedocs.org#12161]
## What's the problem this feature will solve?

ATM, `text` format is not supported.

*Filename: .readthedocs.yaml*

```
# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub
  - text
```

Build results into an error:

```
Config file validation error Config validation error in formats. 

Expected one of (htmlzip, pdf, epub), got type str (text). 

Double check the type of the value. A string may be required (e.g. "3.10" instead of 3.10)
```

## Describe the solution you'd like

I'd like `text` format to be supported.

## Alternative solutions

None.

## Additional context

In case I want to generate my documentation in `text` format. For instance, I want to generate llms.txt which is a concatenated version of all of my main docs.

It works locally (``sphinx-build -n -b text docs builddocs``), but does not work with RTD.

**Comment by humitos** [comment]
Hi @barseghyanartur! You can use `build.jobs.post_build` to execute that command. Take a look at https://docs.readthedocs.com/platform/latest/build-customization.html. Please, let me know if that works for you.

Unfortunately, we don't plan to natively support another format in the near term, but you should be able to `post_build` for your purpose.

**Comment by barseghyanartur** [comment]
@humitos:

Thanks for a quick response. I'll try that.

**Comment by stsewd** [comment]
Probably worth having documentation for this use case

**Comment by humitos** [comment]
@barseghyanartur did it work the solution suggested? If so, would you like to propose a PR with the an example of how you did it to our documentation?

**Comment by barseghyanartur** [comment]
It works!

*Filename: .readthedocs.yaml*

```yaml
# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub
  - htmlzip

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py
  # You can configure Sphinx to use a different builder, for instance use the dirhtml builder for simpler URLs
  # builder: "dirhtml"
  # Fail on all warnings to avoid broken references
  # fail_on_warning: true

# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
  - requirements: docs/requirements.txt

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    # You can also specify other tool versions:
    # nodejs: "20"
    # rust: "1.70"
    # golang: "1.20"
  jobs:
    build:
      # The default commands for generating the HTML and pdf formats will still run.
      htmlzip:
        - echo "Override default build command for htmlzip format"
        - mkdir -p $READTHEDOCS_OUTPUT/html/
        - sphinx-build -n -b text docs $READTHEDOCS_OUTPUT/html/
```

Result:

- [HTML docs (pytest-codeblock.readthedocs.io/en/latest/index.html)](https://pytest-codeblock.readthedocs.io/en/latest/index.html)
- [Text docs (pytest-codeblock.readthedocs.io/en/latest/llms.txt)](https://pytest-codeblock.readthedocs.io/en/latest/llms.txt)
