### ISSUE TITLE
Schema claims tools is a required field

### ISSUE THREAD

**Issue by henryiii** [readthedocs/readthedocs.org#12219]
The schema claims `tools` is required:

https://github.com/readthedocs/readthedocs.org/blob/4add65fc06bbf6a27f419f74ef5f13364430a031/readthedocs/rtd_tests/fixtures/spec/v2/schema.json#L264

But this works:

```yaml
version: 2

build:
  os: ubuntu-24.04
  commands:
    - asdf install python 3.14-dev
    - asdf global python 3.14-dev
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - NO_COLOR=1 uv run --no-dev --group docs mkdocs build --strict --site-dir $READTHEDOCS_OUTPUT/html
```
