### ISSUE TITLE
readthedocs configuration file

### ISSUE THREAD

**Issue by wraithan** [readthedocs/readthedocs.org#248]
Thinking something like .travis.yml or the like for configuration.

``` yaml
name: ZenIRCBot
repo_type: git
repo_url: git://github.com/wraithan/zenircbot.git
requirements: requirements/docs.txt
description:
  This is an irc bot I wrote to be cool like all the other kids
  that write irc bots!
```

Would need to be explicit that the file will overwrite your changes in the web interface or would be ignored in lieu of the web interface, whichever way that ends up going.

Not super tied to the idea, just want some comments/thoughts on it.
