### ISSUE TITLE
Different platform provided requirements

### ISSUE THREAD

**Issue by xrmx** [readthedocs/readthedocs.org#4300]
We'd like to provide more packages available by default to documentation builds. Currently the only hook to provide extra_requirements is by the config or the user conf. I can't see a way for a downstream platform to provide a different set of requirements with the current code. One way would be to make the Virtualenv and Conda classes overridable by settings so one can override `install_core_requirements`. 
Is it something that may be interesting for upstream too? Any opinion on the proposed implementation?

**Comment by humitos** [comment]
We use this pattern to extend which classes can be overrideable:

https://github.com/rtfd/readthedocs.org/blob/4fa2746040aee0aafcdb09e0e5674dcb42ea9809/readthedocs/core/utils/extend.py#L44-L79

when we need to override something from the corporate site that shares the code with the community site.

I suppose that we should be inherit the CondaEnvironment and VirtualenvEnvironment to from SettingsOverrideObject and that will do the trick.

**Comment by humitos** [comment]
I also like the idea of making this configurable by a setting, so we remove them from the middle of the code and we put all of them in the same place. I'm :+1: on this.

We will need to think about how we will implement these conditionals that depends on a FEATURE FLAG in the project itself:

https://github.com/readthedocs/readthedocs.org/blob/1998cf555303b8400b6ab98ed056b1cb061be88f/readthedocs/doc_builder/python_environments.py#L350-L354

**Comment by humitos** [comment]
This is now possible by using "Build customizations" (see https://docs.readthedocs.io/en/latest/build-customization.html). Example:

```yaml
version: 2
build:
  os: ubuntu-22.04
  jobs:
    post_install:
      - pip install <your extra requirements here>
```

Another approach would be to create a `requirements.txt` file and define `python.install` config key:

```yaml
version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3"

python:
  install:
    - requirements: requirements.txt
```
