### ISSUE TITLE
Add option to use -e pip install

### ISSUE THREAD

**Issue by bpeake-illuscio** [readthedocs/readthedocs.org#6243]
Hi all,

I am running into an issue where my builds fail because I cannot perform an egg install with pip.

The way my project is structured, pip needs to have the -e flag set when pip installing in order to see my service's sub-modules, but I don't see any option to do this in the YAML settings.

Instead, during the build I get an error like this, since the library has no .egg: 

`ModuleNotFoundError: No module named 'service.stage_handlers'`

Thanks!

**Comment by stsewd** [comment]
This is the same as https://github.com/readthedocs/readthedocs.org/issues/3986, there is a workaround using a requirements fille with `-e .`

Not sure where we landed on this, I think we wanted to make this the default option.

**Comment by bpeake-illuscio** [comment]
Hi!

I'm looking at the YAML v2 documentation and I'm not sure I see how to add the -e to a requirements.txt install.

Here is my current config:

```
version: 2

build:
  image: latest

python:
  version: 3.7
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc

sphinx:
  builder: html
  fail_on_warning: false

```

How would I modify it? Thank you!

**Comment by stsewd** [comment]
You need to create a `docs/requirements.txt` file with this content

```txt
-e .[doc]
```

And modify your yaml file like this

```yaml
version: 2

build:
  image: latest

python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt

sphinx:
  builder: html
  fail_on_warning: false

```
