### ISSUE TITLE
Build fails permission denied

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckxSimpleRose** [readthedocs/readthedocs.org#6293]
## Details

I'm using the trial account with a private python repo building docs with Sphinx. I've got no issues building docs locally, however the build is failing on RTD.

```
Collecting pip
  Using cached https://files.pythonhosted.org/packages/4a/08/6ca123073af4ebc4c5488a5bc8a010ac57aa39ce4d3c8a931ad504de4185/pip-19.3-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 18.1
    Uninstalling pip-18.1:
      Successfully uninstalled pip-18.1
  Rolling back uninstall of pip
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/lib/python3.7'
Consider using the `--user` option or check the permissions.

You are using pip version 18.1, however version 19.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

* Read the Docs project URL: private repo
* Build URL (if applicable): https://readthedocs.com/api/v2/build/250162.txt
* Read the Docs username (if applicable):

My `.readthedocs.yml` looks like:
```
# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
  builder: html
  fail_on_warning: true

python:
  version: 3.7
  install:
    - requirements: requirements.txt
    - requirements: docs/requirements.txt
```

My docs all live in `docs/`
