### ISSUE TITLE
Command killed due to excessive memory consumption

### ISSUE THREAD

**Issue by lukelbd** [readthedocs/readthedocs.org#6412]
## Details

* Read the Docs project URL: https://proplot.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/proplot/builds/
* Read the Docs username (if applicable): lukelbd

## Expected Result

Successful build.

## Actual Result

Failed build. The conda environment solve step causes excess memory consumption.

I also have  `python.system_packages = True` in my yaml. Maybe I can reduce the environment solve complexity by using the shared packages?  Currently the contents of `environment.yml` are:

```yaml
name: proplot-dev
channels:
  - conda-forge
dependencies:
  - pip
  - numpy
  - xarray
  - pandas
  - matplotlib
  - cartopy
  - basemap
  - nbsphinx
  - sphinx
  - ipython
  - ipykernel
  - pip:
    - lxml
    - pyyaml
    - sphinx_rtd_theme
    - git+https://github.com/lukelbd/sphinx-automodapi@v0.6.proplot-mods
```

But I'm also worried about memory consumption for the `nbsphinx` steps, which generate some fairly high resolution figures. Before this merge I used `nbconvert` to manually generate RST files and synced those.

**Comment by humitos** [comment]
Hi @lukelbd! The main problem here is that `conda` consumes _a lot_ of memory to do the package resolution. We had this problem in the past and it's a known issue in the conda community.

I enabled to flags in your project that could help with this (the most important one, is to update conda at startup, since the latest conda release has some memory consumptions improvements).

I triggered a build already. Let's see how it goes.

**Comment by humitos** [comment]
That didn't help too much. I had to increase the memory limit to 2.5Gb to make the `conda create env` step to pass.

The build is still failing because your `proplot` library is not properly installed in the `conda` environment created, so it failed when importing it from Sphinx. See https://readthedocs.org/projects/proplot/builds/10046893/

**Comment by lukelbd** [comment]
Thanks a lot!

I fixed the failed build by adding proplot to `environment.yml` with a

```yaml
dependencies:
  - pip:
    .. # relative path for installing current proplot master branch
```

But now it fails because I've renamed some classes and class methods. I think it will run if I can call `make clean` on the RTD server. How can I do this?
