### ISSUE TITLE
tensorflow 1.x dependency kills build

### ISSUE THREAD

**Issue by KIC** [readthedocs/readthedocs.org#6537]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/pandas-ml-utils/
* Build URL (if applicable): https://readthedocs.org/projects/pandas-ml-utils/builds/10283494/
* Read the Docs username (if applicable):

## Expected Result

Passing build

## Actual Result

Build fails to provide requirement 

Collecting tensorflow==1.* (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/92/2b/e3af15221da9ff323521565fa3324b0d7c7c5b1d7a8ca66984c8d59cb0ce/tensorflow-1.15.0-cp37-cp37m-manylinux2010_x86_64.whl (412.3MB)
Killed

Command killed due to excessive memory consumption

Actually the build was passing many times, I have got problems only recently.

I am using system packages - so my configuration reads:
```
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.7
  system_packages: true
  install:
    - requirements: docs/requirements.txt
    - requirements: requirements.txt
```
