### ISSUE TITLE
Command killed due to excessive memory consumption on conda env create

### ISSUE THREAD

**Issue by swainn** [readthedocs/readthedocs.org#6814]
## Details

* Read the Docs project URL: http://docs.tethysplatform.org/en/stable/
* Build URL (if applicable): https://readthedocs.org/projects/tethys-platform/builds/10680809/
* Read the Docs username (if applicable): swainn

## Expected Result

Successful build

## Actual Result

Failed build (for about a month)

Fails on this step: conda env create --quiet --name stable --file docs/docs_environment.yml. There is minimal difference between this build and the build that last passed about 1 month and 2 weeks ago: https://readthedocs.org/projects/tethys-platform/builds/10402946/ I've tried wiping the environment, but that didn't do much to help.

Current: .readthedocs.yml

```
version: 2
build:
  image: latest
conda:
    environment: docs/docs_environment.yml
sphinx:
    builder: html
    configuration: docs/conf.py
python:
    version: 3.7
    install:
      - method: pip
        path: .
```
Current docs_environment.yml:

```
# docs_environment.yml
# Configuration file for creating a Conda Environment with dependencies needed for Tethys Platform.
# Create the environment by running the following command (after installing Miniconda):
#   $ conda env create -f docs_environment.yml

name: tethys-docs

channels:
- tethysplatform
- conda-forge
- defaults

dependencies:
- python=3.7
- pip
- tethys_dataset_services>=2.0.0
- django>=2.1
- sphinx==2.2.0
- sphinx-argparse
- pbr
- sphinxcontrib-napoleon
- pip:
    - sphinx_materialdesign_theme
```
