### ISSUE TITLE
Execute shell scripts before build

### ISSUE THREAD

**Issue by belerico** [readthedocs/readthedocs.org#6929]
## Details
It would be nice to permit users to run shell scripts before a build, e.g. I need to use `sed` linux command to substitute a path in a file before the building process, so that a relative image can be properly load 

## Expected Result

Maybe a new section in the .yml called `script` or `before-script` could be added, like the Travis or GitLab ones:
```yml
version: 2

before-script:
  - sed -i "s/path/new_path/1" file.md  # or directly call sh substitute.sh

sphinx:
  builder: html
  fail_on_warning: false
  configuration: docs/source/conf.py

formats: all

python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
    - method: setuptools
      path: .
```

## Actual Result

I think I can come up with a Pythonic solution involving running a function in the sphinx conf.py, but there maybe would be cases in which the python solution could nont be affordable
