### ISSUE TITLE
RTD not picking up python pip installation configuration

### ISSUE THREAD

**Issue by dstansby** [readthedocs/readthedocs.org#7057]
## Details

* Read the Docs project URL: https://docs.heliopy.org/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/heliopy/builds/11014777/
* Read the Docs username (if applicable): dstansby

I have the following  `readthedocs.yml`:
```yml
build:
  image: latest

python:
  version: 3.7
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
```

## Expected Result
readthedocs runs `pip install .[docs]` before running `sphinx_build`.

## Actual Result
readthedocs isn't installing the project using pip before trying to build the docs with `sphinx_build`. https://readthedocs.org/projects/heliopy/builds/11014777/ shows no stage where the project is installed using pip. This matters, because the doc requirements need to be installed. Does anyone have any idea what could be going on? I've tried lots of different things and am stumped!
