### ISSUE TITLE
Error: Invalid "name": {}.readthedocs.yml [0]: Missing key "name"% using rtd-build library.

### ISSUE THREAD

**Issue by aakriti0fnu** [readthedocs/readthedocs.org#7348]
[Following this](https://docs.readthedocs.io/en/stable/config-file/v2.html), I created a below file: 
```
# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Build documentation with MkDocs
#mkdocs:
#  configuration: mkdocs.yml

# Optionally build your docs in additional formats such as PDF
formats:
  - pdf

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
```
added all dependencies in `requirement.txt`:
```
Babel==2.8.0
imagesize==1.2.0
readme-renderer==26.0
Sphinx==3.1.2
sphinx-argparse==0.2.5
sphinx-rtd-theme==0.5.0
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-images==0.9.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-napoleon==0.7
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
```
I was trying to test building documentation using [rtd-build](https://pypi.org/project/readthedocs-build/) so that I can test it locally of any dependencies missing and [avoid build failures on readthedocs](https://docs.readthedocs.io/en/stable/builds.html?highlight=build)!, but whenever I'm trying to use this library, it's giving a weird error.
command
```
rtd-build --outdir=../new_my_builds/
```
Error:
```
Error: Invalid "name": {}/.readthedocs.yml [0]: Missing key "name"%
```
I'm able to build documentation locally via `make html` command in `docs` folder, but building through `rtd-build` giving me a hard time.
Do you know what's letting it fail? even following [this](https://docs.readthedocs.io/en/stable/config-file/v2.html), I can see `name` key where in example!
@humitos
