### ISSUE TITLE
readthedocs.yml not recognized / PR builds not working

### ISSUE THREAD

**Issue by Corvince** [readthedocs/readthedocs.org#7624]
## Details

* Read the Docs project URL: https://mesa.readthedocs.io/en/stable/
* Build URL (if applicable): https://readthedocs.org/projects/mesa/builds/12223822/
* Read the Docs username (if applicable): Corvince

## Expected Result

Debugging a broken (but working wrt readthedocs, just a missing lexar) build I enabled PR builds and added a [`.readthedocs.yml` ](https://github.com/projectmesa/mesa/blob/master/.readthedocs.yml) config file. I expected both things to work

## Actual Result

They didn't. the `.readthedocs.yml` file has the following content, but readthedocs won't use it.

```yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF
formats:
  - pdf

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.7
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
  system_packages: true
```
