### ISSUE TITLE
Project Not Building on readthedocs.org (config.py.tmpl?)

### ISSUE THREAD

**Issue by hysz** [readthedocs/readthedocs.org#7704]
## Details

This afternoon my project stopped building on readthedocs.org. It works locally.

* Read the Docs project URL: https://readthedocs.org/projects/0xprotocol
* Build URL (if applicable): https://readthedocs.org/projects/0xprotocol/builds/12439099/
* Read the Docs username (if applicable): hysz

## Expected Result

The project builds.

## Actual Result

The project fails to build with the error: `ModuleNotFoundError: No module named 'six'`. This error seems to be coming from [config.py.tmpl](https://github.com/readthedocs/readthedocs.org/blob/master/readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl#L20).

**Comment by hysz** [comment]
This workaround worked for me:

1. Created a `.readthedocs.yaml`:
```
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Build documentation with MkDocs
#mkdocs:
#  configuration: mkdocs.yml

# Optionally build your docs in additional formats such as PDF
#formats:
#  - pdf

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
```

2. Created a `docs/requirements.txt` file:

```
six
```

Although I'll leave this open, as it seems that this dependency should be getting installed automatically (and I believe was previously, since I have never had this issue before).
