### ISSUE TITLE
Theme / mkdocs / navigation_depth

### ISSUE THREAD

**Issue by maquejp** [readthedocs/readthedocs.org#7765]
## Details

* Read the Docs project URL: https://spa-0-100-eui.readthedocs.io/
* Build URL (if applicable):
* Read the Docs username (if applicable): maquejp

using the theme mkdocs

## Expected Result

I have multi level header like the following

```
site_name: Create an SPA
site_description: Welcome to Create an SPA from 0 to 100 in nn steps
site_author: Jean-Philippe M
nav:
  - Home: index.md
  - Purpose: purpose.md
  - Technologies: technologies.md
  - Building the application:
      - Start: building.md
theme:
  name: mkdocs
  highlightjs: true
  navigation_depth: 4
```
in the building.md
```
# Building the application

## Installing the necessary tools

### NodeJS

### NPM

## Initialise the applications
```
I am expecting to see in the left menu (page navigation) all my levels (# ## ###).

## Actual Result

I was expecting to see in the left menu (page navigation) all my levels but it shows only up-to the 2nd level (##) .

Maybe I am doing something wrong.
