### ISSUE TITLE
Upgrade setuptools before installation in .readthedocs.yml

### ISSUE THREAD

**Issue by JoelForamitti** [readthedocs/readthedocs.org#7836]
Using a configuration file .readthedocs.yml, I want to upgrade setuptools to a higher version than the default before installing my package. However, the pip command of .readthedocs.yml only takes path as an argument, so how can I call pip to upgrade setuptools?

Here is what I would put into .readthedocs.yml, but I am missing a command where it says ????:

```
version: 2
formats: all
python:
  version: 3.7
  install:
    - method: pip
      ????: setuptools >= 46.4.0
    - method: pip
      path: .
```
