### ISSUE TITLE
MkDocs builds perfectly locally, but gets stuck on Read the Docs

### ISSUE THREAD

**Issue by Johnystar** [readthedocs/readthedocs.org#7865]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/pluralkitpy/
* Build URL (if applicable): https://pluralkit.johnystar.moe/
* Read the Docs username (if applicable): Johnystar_CZ

## Expected Result

Successfully build the docs just like I can do locally with ``mkdocs build`` or ``mkdocs serve``

## Actual Result

Always gets stuck at
```
ERROR   -  Config value: 'markdown_extensions'. Error: unsupported callable 

Aborted with 1 Configuration Errors!
```

I honestly have no clue if this is a bug or if I did something wrong, I at least triple checked everything, so I hope someone more experienced can help me.

**Comment by nmichlo** [comment]
I had exactly the same issue.

The problem is the emoji markdown plugin:
```yaml
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
```

Examining the step just before the error `cat mkdocs.yml`. The problem seems to be that readthedocs generates a custom version of the mkdocs.yml file by parsing it, injecting keys and resaving the file.

This process is not able to handle the oddly formatted values for `emoji_index` and `emoji_generator` which become null.

```yaml
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: null
      emoji_generator: null
```

I have tried quoting these, values but that does not seem to work.
