### ISSUE TITLE
Could not import extension sphinxcontrib-bibtex

### ISSUE THREAD

**Issue by jlconlin** [readthedocs/readthedocs.org#7872]
## Details

* Read the Docs project URL:
  https://readthedocs.org/projects/reconr/
* Build URL (if applicable):
  There are many of these, but they all have the same problem
  https://readthedocs.org/projects/reconr/builds/12864155/
* Read the Docs username (if applicable):
`jlconlin`
* Repository URL
  https://github.com/njoy/RECONR/tree/docs

## Expected Result

I have no trouble building my documentation locally. I have specified my requirements document in the `.readthedocs.yml` file at the root of my repository.

**`.readthedocs.yml`**
```yml
# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Build documentation with MkDocs
#mkdocs:
#  configuration: mkdocs.yml

# Optionally build your docs in additional formats such as PDF and ePub
formats: all

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
```

**`docs/requirements.txt`**
```
 sphinxcontrib-bibtex
```

I have also changed the readthedocs settings to point to the requirements and configuration.

## Actual Result

When readthedocs tries to build my documentation, I get (see [Build URL](https://readthedocs.org/projects/reconr/builds/12864155/) for more details):

```console
Extension error:
Could not import extension sphinxcontrib-bibtex (exception: No module named 'sphinxcontrib-bibtex')
```

I've seen other similar issues, but I haven't been able to get the same results that they have found. Note I am *not* using a Conda environment.
