### ISSUE TITLE
extra_requirements seems not installed

### ISSUE THREAD

**Issue by zillionare** [readthedocs/readthedocs.org#8085]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/test-0717-02/
* Build URL (if applicable):https://readthedocs.org/projects/test-0717-02/builds/13474065/
* Read the Docs username (if applicable): zillionare

## Expected Result

* mkdocs build success

## Actual Result

*build fails due to all required mkdocs plugin/extensions are not installed.

coniguration is v2:
```
version: 2

# Build documentation in the docs/ directory with Sphinx
# sphinx:
#   configuration: docs/conf.py

# Build documentation with MkDocs
mkdocs:
  configuration: mkdocs.yml

build:
  image: 3.7
# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.7
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
 ```
project is build with poetry, and the extra doc:
```
doc = [
    "mkdocs",
    "mkdocs-include-markdown-plugin",
    "mkdocs-material",
    "mkdocstrings",
    "mkdocs-material-extension",
    "mkdocs-autorefs"
    ]
```
works at local.

configuration file name is .readthedocs.yaml, but I have tried .readthedocs.yml, neither work. 

document type is set to "Mkdocs (markdown)" from web page (why cannot specify this in yml?)
