### ISSUE TITLE
Put guide listing on docs front page

### ISSUE THREAD

**Issue by ericholscher** [readthedocs/readthedocs.org#8321]
Currently we have a listing of content on the docs front page, but it doesn't include our guides. We have a listing here: https://docs.readthedocs.io/en/latest/guides/ -- but not on the front page. We should port this list to the front page, so it's discoverable by our users in a nicer way. 

### Initial work

Put the list of guides on the front docs page, manually: https://github.com/readthedocs/readthedocs.org/blame/b3baa7a7a90b78d0c4f730d88b54fdb20ee72805/docs/index.rst#L127

### Bonus Points

Currently, our front-page is manually listed because the default TOCTree output uses a lot of newlines. I think we should find a way to output the content of the TocTree but without newlines, so that we don't have to maintain this list in 2 places.

**Comment by nienn** [comment]
> Currently, our front-page is manually listed because the default TOCTree output uses a lot of newlines. I think we should find a way to output the content of the TocTree but without newlines, so that we don't have to maintain this list in 2 places.

If there isn't a way to avoid those newlines with reStructuredText then I can hack it with a custom css.

**Comment by astrojuanlu** [comment]
Since https://github.com/sphinx-doc/sphinx/commit/f3f41463120c4b7213543c7d8af0a6bfa4ef7013 (forever), "Toctrees are now wrapped in a ``div`` tag with class ``toctree-wrapper`` in HTML output". That could be used to completely restyle the ``ul`` and ``li`` elements.

**Comment by astrojuanlu** [comment]
Just for future ~scorn~ reference, while I was working on this I produced this nasty CSS hack to make the toctree look almost like our current paragraph of links (requires prefixing all `.. toctree::` directives with `.. rst-class:: index-toc`):

```css
.index-toc p.caption {
  font-size: 1em !important;
  display: inline !important;
  font-family: Lato,proxima-nova,Helvetica Neue,Arial,sans-serif !important;
}
/*.index-toc p.caption::before {
  content: "• ";  // Looks ugly
  margin-left: 8px;
}*/
.index-toc p.caption::after {
  content: ": ";
}
.index-toc ul {
  display: inline;
  list-style-type: none !important;
}
.index-toc ul li {
  display: inline !important;
  margin-left:  0 !important;
}
.index-toc ul li+li::before {
  content: " | ";
}
```

![Screenshot 2021-09-23 at 16-13-07 Read the Docs Documentation Simplified — Read the Docs 5 23 6 documentation](https://user-images.githubusercontent.com/316517/134523496-a2788281-1926-4173-8bd3-63e42001f36d.png)


But, apart from the use of `!important`, the display/flow of the elements is probably quite broken.
