### ISSUE TITLE
Build failing `in depart_codearea_latex     assert 'Verbatim' in lines[0]`

### ISSUE THREAD

**Issue by aiqc** [readthedocs/readthedocs.org#8347]
## Details

* Read the Docs project URL: https://aiqc.readthedocs.io
* Build URL (if applicable): https://readthedocs.org/projects/aiqc/builds/14248504/
* Read the Docs username (if applicable): aiqc

---

I just noticed that the past week of builds is failing. 

Locally everything is working fine. Tried running `make clean` again and pushing it up but it still failed.

---

## Trace

```
/envs/latest/bin/python -m sphinx -b latex -D language=en -d _build/doctrees . _build/latex
Running Sphinx v4.1.1
loading translations [en]... done
making output directory... done
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [latex]: all documents
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
processing aiqc.tex... index notebooks/installation notebooks/example_datasets notebooks/keras_binary_classification notebooks/keras_multi-label_classification notebooks/keras_regression notebooks/image_classification notebooks/sequence_classification notebooks/keras_tabular_forecasting notebooks/pytorch_binary_classification notebooks/pytorch_multi-label_classification notebooks/pytorch_regression notebooks/tensorflow_binary_classification notebooks/heterogeneous_features notebooks/visualization notebooks/api_high_level notebooks/api_low_level notebooks/inference mission community links 
resolving references...
done
writing... failed

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/aiqc/envs/latest/lib/python3.7/site-packages/nbsphinx.py", line 2151, in depart_codearea_latex
    assert 'Verbatim' in lines[0]
AssertionError
The full traceback has been saved in /tmp/sphinx-err-f2v5rdx6.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

---

## Env

requirements.txt
```
ipython==7.19.0
nbsphinx>=0.8.6
sphinx_copybutton==0.3.1
sphinx_rtd_theme==0.5.0
sphinxext-opengraph==0.4.1
jinja2>=3.0.1
```

.readthedocs.yml
```
# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Build documentation with MkDocs
#mkdocs:
#  configuration: mkdocs.yml

# Optionally build your docs in additional formats such as PDF
formats:
  - pdf

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
```
