### ISSUE TITLE
RTD installs python module, but can't import it afterwards

### ISSUE THREAD

**Issue by FirefoxMetzger** [readthedocs/readthedocs.org#8357]
I moved the dependencies of my python project from a `setup.cfg` into a `setup.py` (to allow Dependabot pick them up) and since then RTD is unable to correctly generate the docs.

Locally, the docs build fine. If I build the same project on RTD, however, (after migrating the dependencies) then sphinx.autosummary can't import any modules. Similarly, if I add the line `import ropy` (name of the project) into sphinx's `conf.py` the entire build crashes because RTD can't `import ropy` (log attached). 

I am using a `.readthedocs.yaml` which should install the project together with doc-related dependencies. Indeed, the logs show pip building the wheel and then claiming that it was installed. However, this does not seem to be the case. I tried to add the module to the path manually inside the `conf.py`, which allows to `import ropy`, but then breaks later when sub-modules are imported, because they depend on specific versions of external libraries which don't seem to be present. In particular, I need `numpy` in a sufficiently recent version to support `from numpy.typing import ArrayLike`, but this then crashes (build: https://readthedocs.org/projects/robotics-python/builds/14282476/) with an exception that suggests that the required numpy version isn't present.

Any pointers on where I should look to debug this are highly appreciated :)

<details>
<summary>.readthedocs.yaml</summary>

```yaml
# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: doc/source/conf.py

# Optionally build your docs in additional formats such as PDF
formats:
   - pdf

# Optionally set the version of Python and requirements required to build your docs
python:
   install:
    - method: pip
      path: .
      extra_requirements:
        - docs

```

</details>

## Details

* Read the Docs project URL: https://readthedocs.org/projects/robotics-python/
* Build URL (if applicable): https://readthedocs.org/projects/robotics-python/builds/14282652/
* Read the Docs username (if applicable): FirefoxMetzger

## Expected Result

The rendered docs match the local build and sphinx.automodule can import the module.

## Actual Result

sphinx.automodule (and sphinx in general) can not import the module; however, the logs suggest that it has been installed.
