### ISSUE TITLE
mkdocs: Values with special `!` syntax are set to null on mkdocs.yml

### ISSUE THREAD

**Issue by j1elo** [readthedocs/readthedocs.org#8529]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/openvidu/
* Build URL (if applicable): https://readthedocs.org/projects/openvidu/builds/14834239/
* Read the Docs username (if applicable):

Our project is using:

* MkDocs 1.2.2
* [Extra Context](https://www.mkdocs.org/dev-guide/themes/#extra-context) option in `mkdocs.yml`, with the [ENV syntax](https://www.mkdocs.org/user-guide/configuration/#environment-variables) to read environment variables, making the `READTHEDOCS` vars available to the template context:

    ```
    extra:
      READTHEDOCS: !ENV [READTHEDOCS, "(no var)"]
      READTHEDOCS_VERSION: !ENV [READTHEDOCS_VERSION, "(no var)"]
      READTHEDOCS_PROJECT: !ENV [READTHEDOCS_PROJECT, "(no var)"]
    ```

* Attempting to read the RtD environment variables as explained in [Build environment](https://docs.readthedocs.io/en/stable/builds.html#build-environment) and [How do I change behavior when building with Read the Docs?](https://docs.readthedocs.io/en/stable/faq.html#how-do-i-change-behavior-when-building-with-read-the-docs).

## Expected Result

1. The `cat mkdocs.yml` build step should show proper values for env vars `READTHEDOCS`, `READTHEDOCS_VERSION`, and `READTHEDOCS_PROJECT`.

2. A test html file with these contents:

    ```
    console.log("config.extra: {{ config.extra }}");
    console.log("config.extra.READTHEDOCS: {{ config.extra.READTHEDOCS }}");
    console.log("config.extra.READTHEDOCS_VERSION: {{ config.extra.READTHEDOCS_VERSION }}");
    ```

   should print something similar to this in the browser console:

    ```
    config.extra: {'READTHEDOCS': True, 'READTHEDOCS_VERSION': 1.2.3, 'READTHEDOCS_PROJECT': openvidu}
    config.extra.READTHEDOCS: True
    config.extra.READTHEDOCS_VERSION: 1.2.3
    ```

## Actual Result

1. The `cat mkdocs.yml` build step shows that `READTHEDOCS`, `READTHEDOCS_VERSION`, and `READTHEDOCS_PROJECT` are all `null`:

    ```
    extra:
      READTHEDOCS: null
      READTHEDOCS_PROJECT: null
      READTHEDOCS_VERSION: null
    ```

2. The browser console shows this output:

    ```
    config.extra: {'READTHEDOCS': None, 'READTHEDOCS_PROJECT': None, 'READTHEDOCS_VERSION': None}
    config.extra.READTHEDOCS: None
    config.extra.READTHEDOCS_VERSION: None
    ```

## Extra

Question / potential extra bug in the documentation: the technique shown in [How do I change behavior when building with Read the Docs?](https://docs.readthedocs.io/en/stable/faq.html#how-do-i-change-behavior-when-building-with-read-the-docs) would not really work with MkDocs, would it?

The sample is:

```
{% if READTHEDOCS %}
Woo
{% endif %}
```

but in MkDocs the `READTHEDOCS` is not directly available, is it expected to be? (sorry to ask here but is just a yes/no question that seems very relevant given the topic of the issue)
