### ISSUE TITLE
Amend or clarify interaction between `build.tools.python` and `conda.environment`

### ISSUE THREAD

**Issue by astrojuanlu** [readthedocs/readthedocs.org#8595]
If `build.tools.python` is specified with a non-conda version at the same time that `conda.environment` is present, the build fails. See for example:

https://readthedocs.org/projects/salishsea-nowcast/builds/14996913/

`/home/docs/.asdf/installs/python/3.9.7/bin/python: can't open file '/home/docs/checkouts/readthedocs.org/user_builds/salishsea-nowcast/checkouts/latest/env': [Errno 2] No such file or directory`

which corresponds to this configuration file:

```
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

conda:
  environment: envs/environment-rtd.yaml

# Only build HTML and JSON formats
formats: []
```

We should either produce a better error message if this combination is not possible, or reconcile the two options.

(Thanks @douglatornell for the report 🙏🏽)
