### ISSUE TITLE
Deprecate `CONDA_USES_MAMBA`

### ISSUE THREAD

**Issue by astrojuanlu** [readthedocs/readthedocs.org#8623]
Projects willing to use conda on Read the Docs now have an alternative way of doing it that doesn't require our intervention:

```
version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"

conda:
  environment: environment.yml
```

Despite some minor confusion (#8595) this is working already for at least [two](https://readthedocs.org/projects/salishsea-nowcast/builds/15007794/) [projects](https://readthedocs.org/projects/avisogenies/builds/15104002/), and it accelerated the total build time by about 5x, as expected.

We could start by removing mentions of it on our documentation: https://docs.readthedocs.io/en/stable/feature-flags.html?highlight=mamba#available-flags and https://docs.readthedocs.io/en/stable/guides/conda.html?highlight=mamba#troubleshooting, pretend that it doesn't exist, and instead tell users to pick the right `python` interpreter.

Additionally, we could email projects that have the flag enabled (can't check how many of them they are at the moment) and tell them the new solution. But it would surely cause a bit of churn, and I'm not sure if it's worth it.
