### ISSUE TITLE
Tutorial not showing docstrings of API

### ISSUE THREAD

**Issue by jojomale** [readthedocs/readthedocs.org#8631]
## Details

* Read the Docs project URL: https://rtd-tutorial-jo.readthedocs.io/en/latest/
* Build URL (if applicable): https://github.com/jojomale/rtd-tutorial.git
* Read the Docs username (if applicable):

## Expected Result

*Content of docstrings should appear in API*

## Actual Result

*API section remains empty, even though the package seem to be installed*

(There is no "ModuleNotFoundError".)

I followed the tutorial, which at some points states that the API section remains empty because up until then the settings did not tell RTD to install the package so that sphinx.autodoc can find it. Indeed `home/docs/checkouts/readthedocs.org/user_builds/rtd-tutorial-jo/envs/latest/bin/python -m sphinx -b latex -D language=en -d _build/doctrees . _build/latex` issues a warning `autodoc: failed to import function 'get_random_ingredients' from module 'lumache'; the following exception was raised:
No module named 'lumache'`.  At this point I added .readthedocs.yaml according to the tutorial: 

```
version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"

python:
  version: "3.9"
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
```

Here are a few problems:

1.  RTD throws an error `Problem in your project's configuration. Invalid "python.version": .readthedocs.yaml: Invalid   configuration option: python.version. Make sure the key name is correct.`

2.    Removing line `version: "3.9"` continues the process, the autodoc warning disappears but there are still no content in the API section.

What am I doing wrong? It would be nice if at least the tutorial worked. It mostly bothers me because the same issue occurs in the project that I am actually working on.
