### ISSUE TITLE
wxpython dependency causes build failure

### ISSUE THREAD

**Issue by rowlesmr** [readthedocs/readthedocs.org#8656]
## Details

* Read the Docs project URL: https://pvct.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/pvct/builds/15219047/

## Expected Result

A successful build

## Actual Result

Build fails due to wxpython dependency given in setup.py

The dependency is not necessary for the document build process.

Similar to #7221

**Comment by rowlesmr** [comment]
This is the original configuration file which fails due to GTK+ not being present
```
.readthedocs.yml: 
version: 2
sphinx:
  configuration: docs/conf.py
formats: all
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
```


This is the modified configuration file which passes due to not actually building the python side of things
```
.readthedocs.yml: 
version: 2
sphinx:
  configuration: docs/conf.py
formats: all
```

Following the guides given in #7221, the GTK+ dependency can be installed. This is the configuration file which fails somewhere during building the wxpython wheel.
```
version: 2
build:
  apt_packages:
    - libgtk-3-dev
sphinx:
  configuration: docs/conf.py
formats: all
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
```

**Comment by astrojuanlu** [comment]
Looks like the compilation works, but something makes the last step fail: https://stackoverflow.com/q/58712734/554319

**Comment by astrojuanlu** [comment]
I suspect that the default Python is statically linked, and wonder if the asdf-installed versions are dynamically linked. Can you try this?

```
version: 2
build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"
  apt_packages:
    - libgtk-3-dev
sphinx:
  configuration: docs/conf.py
formats: all
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
```
