### ISSUE TITLE
using configuration file results in builder without graphviz

### ISSUE THREAD

**Issue by rokroskar** [readthedocs/readthedocs.org#8672]
Our project contains graphviz directives and uses the sphinx graphviz extension. This has worked very well for years on RTD. A few days ago we added a `.readthedocs.yaml` file:

```yaml
version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

sphinx:
  configuration: docs/conf.py

python:
  install:
  - requirements: docs/requirements.txt

submodules:
  include: all
```

If this file is in the project, `dot` is not found and the graphviz graphs don't render. I assume this is a problem with the builder since I can't find any place to state that graphviz should be installed/used.
