### ISSUE TITLE
.readthedocs.yaml not being read

### ISSUE THREAD

**Issue by SamTov** [readthedocs/readthedocs.org#8735]
## Details

It seems that the RTD server is not reading my .readthedocs.yaml file when triggering a build.

* Read the Docs project URL: https://readthedocs.org/projects/mdsuite/
* Build URL: https://readthedocs.org/projects/mdsuite/builds/15422205/
* Read the Docs username (if applicable): SamTov

config file:

```yaml
version: 1

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: requirements.txt
    - requirements: dev-requirements.txt
```

## Expected Result

* Specifically in the config file I have it run pip install from two different requirements files.

## Actual Result

*Appears to generate its own config file and ignore mine.
