### ISSUE TITLE
Config file: support for multiple config files in a project

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#8811]
Currently, the path of the config file can't be changed, it always is `.readthedocs.yaml` and should be at the root of the repo.

But there are users with monorepos that have several projects and their docs in one repo, so using a config file isn't something they can do, they will need to use the settings from the UI, which limit the options they can set and makes them hard to track.

By being able to change the path of the config file per-project, those users would be able to have a better experience. So, the question is how to expose this option, I have two suggestions:

- Using an env var to define the path: something like `RTD_CONFIG=subproject/readthedocs.yaml`
  - This doesn't require adding a new option in the UI or a new field in our DB, but since we don't show the value of env vars after they are created, it's hard to know what path we are using for a given project.
- Creating a new field `project.config_path`.
  - This is more explicit, if the field is empty (default) then we use our current logic to discover the config file, otherwise we use that path.

So, I'm more inclined to option B, do you have another idea of how to implement it?

**Comment by stsewd** [comment]
> I don't understand option B: where would `project.config_path` be?

That's an option on the project admin UI.

**Comment by humitos** [comment]
I think this is a good case to come back to "project level configs Vs. version level configs" discussion and try to solve the problem in a more general way. Make a decision, plan the path going forward, and create the basic structure to keep adding "project level configs" in a clean way in the future.

We have discussed this in #6046, #4221, #5478, #8678 (there are more issues) and we also have some cards in our Trello.

> NOTE that the field proposed here will be a project-level config that will affect _all the versions_ for this project

I think this new field proposed is probably the first step towards the general solution, but I'd like to see a plan involving this thinking a little more. For example:

- add the field `.config_file_path` that points to the "all the version-level configs"
- set project-level settings somehow
  a. on the config file, we can add a new key `.project_level_config_path` (which points to another YAML file with all the project-level configs)
  b. add another field to the `Project` object in the db: `.global_config_path`, pointing to the new YAML file with all the project-level configs
- the configs from the new `.yaml` overrides the settings in the db and save them

I'm not saying this solution is good, but I think we need to think something among these lines to solve this problem and start building the new features on top of the decision we make here.

**Comment by stsewd** [comment]
Not sure if that solves the problem, or if I understand your solution. If the option is defined on a file on the repo, the user can't have different values for the same repo on the same commit/branch (which is the problem on a monorepo).

**Comment by humitos** [comment]
To have different configs/settings for the same branch you need to have two different `readthedocs.yaml` (e.g. `readthedocs.a.yaml` (e.g. builds documentation in `docs/a`) and `readthedocs.b.yaml` (e.g. builds documentation in `docs/b`) in that branch. So, I'm saying the config file path can be defined in the `Project` object adding a new file as you suggested.

Besides, I'm saying that we need _another_ config file path for "project-level configs" where the user can set up as `readthedocs.a.global.yaml` (e.g. this one enables PR builder) or `readthedocs.b.global.yaml` (e.g. this one does not). This _another_ config file can be defined in the `readthedocs.a.yaml` (option a) from my previous comment) or in another `Project` object field (option b) from my previous comment)

I'm not proposing a final solution. However, I'm saying that we need to figure out how to do this in a clean way.

**Comment by agjohnson** [comment]
That is a great point @humitos :100: 

To back up just a bit: to support monorepos we can solve this purely at the Sphinx level, configured via env vars, and that does at least work. We could still decide this isn't a good fit for our application and solve this outside, via Sphinx extension. I would be okay if we ended here, because this isn't a widely requested feature at the end of the day.

Okay, so now if we do want to support this natively, I came to the same conclusion as Manuel.

We can tell users to use a singular python requirements file in a monorepo, but users probably would still want per-project configuration of:

* Search tweaks
* Build formats?
* Redirects (big oof here)

When we get to redirects, we need per-project and per-version configuration. So we need two files to support this. But once we also factor in monorepo support, we're talking about multiple *sets* of these configuration files -- as noted above.

We have a few potential options:

* A filename postfix like described above. State is stored at something like `Project.configuration_postfix`. Functionally similar to a `Project.configuration_path`, but this needs to affect both a `.readthedocs.{postfix}.yaml` and a `.readthedocs-global.{postfix}.yaml`
* Use configuration file namespaces/overrides, and still just one set of `.readthedocs.yaml` and `.readthedocs-global.yaml`
* Dynamic configuration or configuration file templating

----

Namespacing isn't as awful as it sounds. Consider something like this:

```yaml

version: 2

formats: all

sphinx:
  configuration: docs/conf.py

overrides:
  "api-docs":
    sphinx:
      configuration: docs/api/conf.py
    search: {}
  "site-docs":
    sphinx:
      configuration: docs/site/conf.py
  "dev-docs":
    sphinx:
      configuration: docs/dev/conf.py

search:
  ranking:
    # Deprecated content
    api/v1.html: -1
    config-file/v1.html: -1

    # Useful content, but not something we want most users finding
    changelog.html: -6
```

`overrides` is applied last, and uses a `Project.configuration_namespace` to merge the overrides into the configuration object. This keeps a singular set of configuration files at least. This is maybe easier to communicate as a pattern to users than multiple sets of files. It's quite clean too.

---

Dynamic configuration is maybe a :exploding_head: solution, but it can also solve future configuration problems and provides a lot of flexibility to users. We're handing out foot guns with this, but you're already advanced usage if you want multiple project support.

Looking at some prior art, CircleCI has a feature for monorepo usage, called dynamic config:
https://circleci.com/docs/2.0/dynamic-config/

It's a script that generates the configuration file used in the build. It's a heavy solution, and quite weird, but could be inspiration.

But, that got me thinking, what about jinja template YAML?

```yaml

version: 2

formats: all

# Basic templating can be used for variables
sphinx:
  configuration: docs/{{ readthedocs.project_slug }}/conf.py

# But we even have includes on our config
{% if readthedocs.project_slug == 'foo' %}
  {% include '.readthedocs/foo.yaml' %}
{% endif %}
```

----

Namespaces/overrides seems like a sweet spot for advanced usage and maintainability/support on our side.

I could see some incredibly cool things coming from template support though, but it's more of an expert level feature given you need to know jinja syntax too.

Anyways, I agree with Manuel, now is a good time to think ahead to a global configuration file. It would help to consider how we might use a global configuration file and how this might shape up that spec -- though we can simmer on an actionable plan for both redirects and global configuration.

**Comment by stsewd** [comment]
I think explicit is better, but also having two config files would be confusing (I'm talking about the idea to have one config file for global settings and another one for per-version settings).

If we have two files for global and per-version settings, we still need to choose from what branch/version we read that file, if we go with reading global options from the default version or latest, we can just use the same config file, adding the settings under the "global" key, something like:

```yaml
version: 2

formats: all

sphinx:
  configuration: docs/conf.py

search:
  ranking:
    # Deprecated content
    api/v1.html: -1
    config-file/v1.html: -1

global-settings:
  redirects: ?
```

For the monorepo support, I still think having a setting on the admin is a good place for it instead of a file (so we don't need to guess from what file to read this setting that will tell us from what other file read the real settings), and will also give more flexibility about where to put the file, each config under each subdirectory (but we need to be explicit about relative and absolute paths).

> Use configuration file namespaces/overrides, and still just one set of .readthedocs.yaml and .readthedocs-global.yaml

This is mainly to share the same config between projects, but I think most of the time there is little to share, like search the paths on each project will be different, and will also bring confusion about what overrides what (are values merged or replaced?).
