### ISSUE TITLE
Support alternative warning banner for PR builds

### ISSUE THREAD

**Issue by sirosen** [readthedocs/readthedocs.org#8910]
Not to bury the lede, I think it would be cool if I could replace the generated warning with an announcement for the Furo theme: https://pradyunsg.me/furo/customisation/#announcement

Furo is pretty popular, but I don't know that it merits special consideration. Would it be possible to add a hook step for handling the warning banner? This could also perhaps be used as a way to support non-sphinx projects.

I'm imagining a new value in config:
```
build:
  # some script hook, which defaults to the current behavior
  pr_warning_hook:
    script: docs/set_furo_hook.py
```
and if new builtin behaviors are added, they could be specified under the same section, with a key other than `script`.
