### ISSUE TITLE
Better error message when using `build.tools.python` without `build.os`

### ISSUE THREAD

**Issue by adamjstewart** [readthedocs/readthedocs.org#8912]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/fiscalyear/
* Build URL (if applicable): https://readthedocs.org/projects/fiscalyear/builds/16068109/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/adamjstewart/

## Expected Result

I would expect the following simple `.readthedocs.yaml` file to work:
```yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python
build:
  tools:
    python: "3.10"

# Configuration for Sphinx documentation
sphinx:
   configuration: docs/conf.py
   fail_on_warning: true
```

## Actual Result

I see the following build error:

> Problem in your project's configuration. Invalid "build.tools.python": .readthedocs.yaml: Invalid configuration option: build.tools.python. Make sure the key name is correct.

For now I'll just remove this option.

**Comment by choi-jiwoo** [comment]
Had same issue when building documentation of my project, and found out that I had to configure `build.os` before `build.tools`. It is stated as a **Required** field in their [documentation](https://docs.readthedocs.io/en/stable/index.html).

See the documentation about `build.os` [here](https://docs.readthedocs.io/en/stable/config-file/v2.html#build-os).

```yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python
build:
  os: ubuntu-20.04  # <- add this line
  tools:
    python: "3.10"

# Configuration for Sphinx documentation
sphinx:
   configuration: docs/conf.py
   fail_on_warning: true
```
