### ISSUE TITLE
Allow direct specification of Python requirements in .readthedocs.yaml

### ISSUE THREAD

**Issue by mcarans** [readthedocs/readthedocs.org#8956]
Thanks for a useful project. Currently you can specify Python requirements in a file and put the path in .readthedocs.yaml. I want to suggest specifying requirements directly in .readthedocs.yaml to reduce the number of configuration files needed eg. something like

```yaml
version: 2
mkdocs: {}  # tell readthedocs to use mkdocs
python:
  version: 3.7
  install:
  - dependencies: 
     - "pydoc-markdown"
     - "readthedocs-custom-steps==0.5.1"
```
