### ISSUE TITLE
Allow custom steps in .readthedocs.yml

### ISSUE THREAD

**Issue by mcarans** [readthedocs/readthedocs.org#8963]
Currently to run custom steps in the readthedocs build process requires using a library [readthedocs-custom-steps](https://github.com/NiklasRosenstein/readthedocs-custom-steps). it would be great if it were possible to run custom steps directly in .readthedocs.yml. This would need to be combined with direct specification of Python requirements in .readthedocs.yml as has previously been raised in https://github.com/readthedocs/readthedocs.org/issues/5572.

I could envisage something like the following:

.readthedocs.yml
```yaml
version: 2
mkdocs: {}  # tell readthedocs to use mkdocs
python:
  version: 3.7
  install:
  - packages:
    - pydoc-markdown
    - readthedocs-custom-steps
  run:
    - pydoc-markdown --build --site-dir "$PWD/_build/html"
```

This would replace using readthedocs-custom-steps as follows:

.readthedocs.yml
```yaml
version: 2
mkdocs: {}  # tell readthedocs to use mkdocs
python:
  version: 3.7
  install:
  - requirements: docs/.readthedocs-requirements.txt
```

docs/.readthedocs-requirements.txt
```
pydoc-markdown
readthedocs-custom-steps
```

pyroject.toml:
```toml
[tool.readthedocs-custom-steps]
script = """
pydoc-markdown --build --site-dir "$PWD/_build/html"
"""
```

**Comment by humitos** [comment]
Hi! Thanks for opening this issue. We have been considering adding custom steps/commands already but we haven't had the time to jump into this, yet. We created some design documents to discuss these ideas in https://github.com/readthedocs/readthedocs.org/pull/8190 and https://github.com/readthedocs/readthedocs.org/pull/8215. Please, provide any feedback you may have on those PRs that are the ones that we will come back to when we start working on this. Thanks!

**Comment by humitos** [comment]
Hi! In a few hours, we are deploying a new feature that will allow people to call arbitrary commands at different moments in the build process. For example,

```yaml
build:
  jobs:
    post_install:
      - pydoc-markdown --build --site-dir "$PWD/_build/html"
```

I think this new config key, `build.jobs`, will cover this case. Take a look at the documentation at https://docs.readthedocs.io/en/latest/config-file/v2.html#build-jobs and please let me know if this is useful for you.
