### ISSUE TITLE
Documentation build failed when calling command from package that is already installed

### ISSUE THREAD

**Issue by Zlopez** [readthedocs/readthedocs.org#8993]
## Details

For installation of the project in build environment I need to have krb5-config installed. So I set my build environment like this:
```
# Configure build environment
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  apt_packages:
    - krb5-config
```

According to the build logs the `krb5-config` is installed, but when trying to build the project it fails on `krb5-config` command not found.

* Read the Docs project URL: https://readthedocs.org/projects/fmn/
* Build URL (if applicable): https://readthedocs.org/projects/fmn/builds/16255577/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/Zlopez/

## Expected Result

The build should find krb5-config command

## Actual Result

`/bin/sh: 1: krb5-config: not found`
