### ISSUE TITLE
Build: implement build output contract

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#9088]
This is what so far has been called "metadata.yaml".

@humitos has the most background on what this work is.

Originally discussed in a draft PR here: https://github.com/readthedocs/readthedocs.org/pull/8190 and some notes on hackmd from a meeting.

**Comment by agjohnson** [comment]
I think structure is mostly figured out here.

We do need the build contract eventually, as we'll also use this file to support upload of HTML tarballs.

I'd advocate for a clearer and more unique file name than `metadata.yaml` though -- `doc-output.yaml`, `docs.yaml`, `artifacts.yaml`, etc.

**Comment by humitos** [comment]
> A conversation for a second implementation, but I'd love to see some way to bring the contract file and `readthedocs.yaml` together. I can't think of a reason why that's needed up front

I wrote about why I think it's a good idea to have this in a separate file in https://github.com/readthedocs/readthedocs.org/pull/8190#discussion_r636080468

**Comment by agjohnson** [comment]
That discussion seems limited to whether or not the configuration file is better in `readthedocs.yaml` or as a separate file. I'm not describing keeping this as static configuration in `readthedocs.yaml`

> I'm describing `{build: {jobs: {collect_artifacts: cat metadata.yaml}}}` as the effective command users could override.

We'd treat this as a build step, to surface the interaction between our build process and the contract file to users. Otherwise, it's a magical file that does something if we encounter it.

**Comment by humitos** [comment]
Oh, I think I misunderstood your point originally then. I agree with `collect_artifacts` being a build step 👍🏼 --I'm sorry for the noise 😄

**Comment by agjohnson** [comment]
It might be worth reviewing this plan and discussing more, but I think we lean towards starting with communicating/documenting the output paths and anything else strictly necessary for build.jobs/commands usage and maybe pausing on the rest of the contract file.

@humitos is there anything else in the contract file besides the output paths the you feel is necessary?

**Comment by ericholscher** [comment]
To clarify, it feels like we're defining the contract incrementally each time we implement things, instead of all at once. It feels like we're mostly defining things by convention, and using YAML config data for the rest currently.

**Comment by humitos** [comment]
I'm not sure to understand what you are asking here. Can you expand?

Currently, we only have implemented the "output path" (just `_readthedocs/html`). There is no way to interact with the build process/hosting itself in any other way than just putting files there.

The original idea of this was:

```
input.yaml -> build process -> output.yaml -> hosting
```

The only thing implemented currently is the `readthedocs.html_output` from the `output.yaml`.

**Comment by agjohnson** [comment]
What I'm ultimately asking is: do we even need a contract file?

Output paths are required, but I don't see a need to make them configurable. Convention here seems like it's plenty, as long as we communicate these somewhere for users.

* HTML output goes in `_readthedocs/html`
* PDF output goes in `_readthedocs/pdf`
* EPUB output goes in `_readthedocs/epub`
* HTMLzip output goes in `_readthedocs/htmlzip`

(We might need to specify a filename for other formats though, as we only support one file per output type, but that's another conversation)

Past that, it's not really clear we have a need for a separate contract file or additional configuration at all perhaps.

For example, you originally highlighted some ideas here:

https://github.com/readthedocs/readthedocs.org/pull/8190/files#diff-88e870e051679647ed5d25f90e929304026661c768ad12165e3e6f1da7276d6cR118-R124

But these seem like they could either be in `.readthedocs.yaml`, or may not even need to be configuration options at all. Or might be JS integration points in our library.

Are there any configuration options besides output paths that you feel are necessary @humitos ?

**Comment by Jackenmen** [comment]
Could it be determined whether a format will be built at runtime? For example, I could want to only build HTML for PRs to make the build take less time and allow to see the preview quicker but build all formats when building from the main branch or tag so that they're actually built when it matters.

I imagine it could be possible simply by not creating the `_readthedocs/pdf` file/directory during the build based on the condition I specified above but I'm not sure if you envision it like that or if not creating such a file would cause the whole build to fail.

**Comment by humitos** [comment]
@agjohnson 

> What I'm ultimately asking is: do we even need a contract file?

We need a contract file because we want to output a lot more information than just "where the output files are".

If you are asking "do wee need a contract file _for this particular case_?". I'd say we may not --we are already doing this for `_readthedocs/html`.

> (We might need to specify a filename for other formats though, as we only support one file per output type, but that's another conversation)

If we are using a convention for the PDF output's path, we can use a convention for this as well: "if you have multiple `.pdf` files in `_readthedocs/pdf`, we will serve them all".

> Are there any configuration options besides output paths that you feel are necessary @humitos ?

I mean, yes. That's why I wrote the original design doc [^1]. I feel that we are recovering that old _long_ conversation we had here. If that's the plan, I need to sit down again and re-read all the documents and notes we have around; but I'd ask other people to do the same so we are all in the same page because this "simple" question does not have a quick answer.

I'm fine changing directions here if needed, since some things have changed already. However, I'd suggest to not do that without reviewing all those conversations and documents.

Also, we are again breaking this conversation in multiple issues which makes everything more confusing. We are also talking about `_readthedocs/pdf` in https://github.com/readthedocs/meta/issues/77

[^1]: the build contract not only tells us where the files are, or what's the doctool used to build the docs; it opens the door to be _documentation tool agnostic_ while keeping the resulting documentation 100% integrated with Read the Docs

**Comment by agjohnson** [comment]
> "if you have multiple .pdf files in _readthedocs/pdf, we will serve them all"

Well, eventually :smile: 

We have to make the rest of RTD aware of multiple PDF files first. I wouldn't take that work on yet, nor would I pre-optimize our implementation here for this constraint yet. It seems fine to start with support for single files first in our convention -- `_readthedocs/pdf/output.pdf` or whatever seems easy to communicate.

We can update our convention to support multiple files later, but it's still not clear we need secondary configuration here.

> I'm fine changing directions here if needed, since some things have changed already. However, I'd suggest to not do that without reviewing all those conversations and documents.

I'm mostly asking for clarification, not a change in direction. We started a change in direction already by moving towards convention over configuration. This provides users with the same functionality in a much easier to maintain way for us, and likely is easier for users to use as well. I think is an important point.

I was asking about the other configuration options specifically [above](https://github.com/readthedocs/readthedocs.org/issues/9088#issuecomment-1325543274). I noted that it's not clear anymore why those need to be in a secondary configuration file.

We already have trouble with one configuration file, two configuration files seems like it will slow us down too much. But with part of this contract already defined by convention, we'd need a strong reason to implement the remaining options in a secondary configuration file.

> Also, we are again breaking this conversation in multiple issues which makes everything more confusing.

I'm discussing this at a top level here as the rest of the contract file is something we need to place/remove from our roadmap. I think discussion around `_readthedocs/pdf` convention addition is separate and already ongoing and don't want to derail conversation at readthedocs/meta#77 with this.

**Comment by humitos** [comment]
@agjohnson 

> We already have trouble with one configuration file, two configuration files seems like it will slow us down too much. But with part of this contract already defined by convention, we'd need a strong reason to implement the remaining options in a secondary configuration file and take on this work in our roadmap.

I'm fine using conventions where it's possible. However, if we want more people/doctools to integrate with us, we need to give them flexibility instead of forcing them to do things exactly as we want. There is a trade off here, of course.

I don't have a strong preference for a separate file. I think it's enough with your idea of using a `build.jobs` command to collect the contract data. What I really want is to have a well-defined contract for:

- hosting integrations
- telemetry

An example of what I'm thinking here:

```yaml
build:
  jobs:
    # Override default jobs:
    # It won't install "readthedocs-sphinx-ext" for example
    install:
      - pip install -r docs/requirements.txt

    # It won't run the default "sphinx-build" command for HTML nor PDF,
    # but a modified one by the user.
    # It uses conventions for the output directory.
    html:
      - python -m sphinx -b html docs/ _readthedocs/html
    pdf:
      - sphinx-build -b simplepdf docs/ _readthedocs/pdf/

    pre_metadata: null
    metadata:
      # Telemetry
      doctool:
       name: sphinx
       version: 5.0.1
       builder: html
       extensions:
         - autoapi
         - hoverxref
       theme: furo
      
      # Hosting integrations
      readthedocs:
       # It uses a convention to inject it in the following div
       #   <div id="readthedocs-embed-flyout"></div>
       flyout: true

       # Here we need to figure it out how we are going to implement
       # all the integrations we have in `readthedocs-sphinx-ext` since
       # people is not going to install this extension anymore.
       # These integrations have to be migrated into Javascript and enabled
       # and configured from here.
    post_metadata: null
```

Note that I'm using `build.jobs.metadata` to communicate all these things to Read the Docs. Here we could have all the items statically defined for the contract itself, or it can be a command that loads the YAML (as you suggested in a previous comment: `cat metadata.yaml` or `python metadata.py`). There are some information that requires being dynamically collected (like Telemetry data) --we are currently outputting a `telemetry.json` from inside the Sphinx build's process; but we need to migrate this outside the `readthedocs-sphinx-ext` in a similar way we are migrating all the other integrations.

The exact contract structure will be defined from the research we are doing in https://github.com/readthedocs/meta/issues/85#issuecomment-1329920589 and also in https://github.com/readthedocs/readthedocs.org/pull/9755#issuecomment-1329004648. IMO, the first step here is migrating all the injections performed at build time to live in a Javascript library; being it the only file we inject on all the pages.
