### ISSUE TITLE
Build failed on Read the Docs

### ISSUE THREAD

**Issue by ka2in** [readthedocs/readthedocs.org#9174]
Hi all,

I'm trying to publish a sphinx project on Read the Docs. Everything works fine on my local environment, but the process fails on Read the Docs with the output below. Thank you for your help!

```Running Sphinx v4.5.0
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/fossdocs/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 425, in load_extension
    mod = import_module(extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fossdocs/envs/latest/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'myst_parser'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/fossdocs/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 275, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fossdocs/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 223, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fossdocs/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 380, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fossdocs/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 429, in load_extension
    err) from err
sphinx.errors.ExtensionError: Could not import extension myst_parser (exception: No module named 'myst_parser')
Extension error:
Could not import extension myst_parser (exception: No module named 'myst_parser')

**Comment by ka2in** [comment]
Sorry for the inconvenience. I've managed to resolve the issue by myself by adding the following changes to my configuration:

```
# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  image: testing

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/source/conf.py

# Optionally build your docs in additional formats such as PDF
formats: all

# Optionally set the version of Python and requirements required to build your docs
python:
  version: "3.9"
  install:
  - requirements:
      docs/requirements.txt
```
In the YAML file above, I'm using python version 3.9 with the image build set to `testing`.

Then I specify the package version explicitly in my `requirements.txt` file:
```
myst_parser==0.15.2
```
In my case, I'm checking the package version with the command:

```
pip show  myst_parser
```

Note that the official documentation also states that you should be [pinning dependencies](https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html#id4) instead of relying on implicit package versions.

**Comment by ka2in** [comment]
Hi @humitos: Thank you very much for letting me know! :thumbsup:
When I changed my settings yesterday, Read the Docs built the documentation successfully without complaining about any deprecated keys. :thinking: 
That being said, I will update my config key to `build.os` and run a new rebuild.

**Comment by humitos** [comment]
Yeah, we are not communicating this in the UI yet. We plan to improve our notifications system to be able to communicate these things properly.

**Comment by ka2in** [comment]
Hi all,

Following the advice of @humitos, my ``.yaml``config file now looks like this:

```
# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/source/conf.py

# Optionally build your docs in additional formats such as PDF
formats: all

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
  - requirements:
      docs/requirements.txt
```
The build completes now without any issues. 🚀 
Here's more info about [RTD docker images](https://github.com/readthedocs/readthedocs-docker-images).
