### ISSUE TITLE
Config: add `cache` key to save state between builds

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#9183]
I'm not sure if this is a too-requested feature, but I wanted to open this issue to start the conversation at least and collect 👍🏼's via GitHub _reactions_ in case people want this feature to be implemented.

Currently, we are allowing users to use `build.jobs` to run custom commands in the middle of the build process. There are some projects that are already running some CPU/bandwidth intense actions there and they may have some benefit by caching some directories.

### Initial implementation

I'm thinking the _basic_ implementation for this would be something like:

```yaml
build:
  pre_build:
    - bash cpu_intense_script.sh >  /path/to/my/cached/directory/file.out
  cache:
    - "/path/to/my/cached/directory"
    - "/home/docs/.pip/cache"
    - ...
```

The implementation can be done with the code we used to have: [`CachedEnvironmentMixin`](https://github.com/readthedocs/readthedocs.org/blob/959443590ccf2008ca0ddc394b1da2510843d44a/readthedocs/projects/tasks.py#L84)

  - compress into `.tar.gz` and upload to S3 the paths defined by the user after the build finishes
  - at the beginning of the build will download from S3 cached paths if there are any

### Questions

  - what are the most common use cases for cache?
  - what kind of integrations do we want to implement for this feature?
  - how do we know that a cache path has to be purged?
  - should we cache and retrieve each path independently?
  - should PR _and_ normal builds allow to use the cache? should this be configurable at project level?
  - what's the minimal time where using a cached directory makes it faster than running the command itself?
