### ISSUE TITLE
Build fails when creating conda env

### ISSUE THREAD

**Issue by nicrie** [readthedocs/readthedocs.org#9527]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/xeofs/
* Build URL (if applicable): https://readthedocs.org/projects/xeofs/builds/17851802/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/nrieger/

## Expected Result

Building package documentation.

## Actual Result

Build fails when creating the conda environment necessary for my project. It did work in the past when I did the last project update. 

## readthedocs.yaml
```yaml
version: 2

sphinx:
   configuration: docs/conf.py


conda:
  environment: docs/environment.yml
```

## environment.yml
```yaml
name: xeofs
channels:
  - conda-forge
  - defaults
dependencies:
  - python>3.8
  - numpy
  - pandas
  - xarray
  - conda
  - scikit-learn
  - yaml
  - matplotlib
  - seaborn
  - pip:
    - sphinxawesome-theme
    - git+https://github.com/sphinx-gallery/sphinx-gallery.git@master
    - xeofs
```
