### ISSUE TITLE
Config: `build.tools.python` has to be a string to avoid confusions

### ISSUE THREAD

**Issue by webknjaz** [readthedocs/readthedocs.org#9719]
## Details

RTD build page presents an error message that doesn't make sense.

* Read the Docs project URL: https://readthedocs.org/projects/tomlkit-webknjazs-fork
* Build URL (if applicable): 
https://readthedocs.org/projects/tomlkit-webknjazs-fork/builds/18577928/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/webknjaz/

## Expected Result

Build should start.

## Actual Result

It didn't. Instead, it errored out with a banner saying:

> Problem in your project's configuration. Invalid "build.tools.python": expected one of (2.7, 3.6, 3.7, 3.8, 3.9, 3.10, **_3.11_**, pypy3.7, pypy3.8, pypy3.9, miniconda3-4.7, mambaforge-4.10, 3), got **_3.11_**

(emphasis mine)
The message says that `3.11` is not a valid version and lists `3.11` among valid versions. That is confusing. Also, the docs page at https://docs.readthedocs.io/en/stable/config-file/v2.html#sphinx-configuration says `3.11` is allowed.

The config file used:
```yaml
---

# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html
# for details

version: 2

sphinx:
  builder: dirhtml
  configuration: docs/conf.py
  fail_on_warning: true

build:
  os: ubuntu-22.04
  tools:
    python: 3.11

python:
  install:
  - method: pip
    path: .
  - requirements: docs/requirements.txt
  system_packages: false

...
```
