### ISSUE TITLE
Install step runs `python -m pip install --upgrade --upgrade-strategy eager` and clobbers most of conda's installed packages

### ISSUE THREAD

**Issue by valeriupredoi** [readthedocs/readthedocs.org#9727]
Hi guys, first off let me just say a big thank you for all your work here, we are happily using Readthedocs, just like many others, and it's great! Second, my apologies if this issue has been discussed elsewhere and decisions were taken, but I thought I'd bring it forward, even if we actually found a solution for it (see below).

So - a vanilla install and build configuration when needing some extra deps (ie install the package that the docs are built for) looks like this (what we had until yesterday):

```yaml
# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-4.10"

# Declare the requirements required to build your docs
conda:
  environment:
    environment.yml

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc

# Build documentation in the doc directory with Sphinx
sphinx:
  configuration: doc/sphinx/source/conf.py
  fail_on_warning: true

# If using Sphinx, optionally build your docs in additional formats such as PDF
formats:
  - pdf
```

and this worked fine for us until `xgboost` had an issue whereby their PyPi version was different from the conda-forge package version - quite normal during a release cycle, when usually PyPi is ahead of conda-forge by a couple days. Only then I noticed that the pip install performed by the workflow from Readthedocs is doing a full eager install of all packages, even if most of them have been installed via the conda env. This is not optimal for a few reasons - it takes longer, issues could arise from package version conflicts, pip may install a package that is literally broken ie a PyPi version may be compiled differently and not play well in a conda env, etc. So I was wondering if you could support user opts for the pip install, with a default a la `pip install .` Let me know if I can help in any way BTW - I tend to open issues that I also want to help with!

We have found a workaround this by using `jobs` - and cheers for implementing that! We are literally just pip installing editable as a post env build step:
```yaml
# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-4.10"
  jobs:
    post_create_environment:
      - pip install -e .[develop]

# Declare the requirements required to build your docs
conda:
  environment:
    environment.yml

# Build documentation in the doc directory with Sphinx
sphinx:
  configuration: doc/sphinx/source/conf.py
  fail_on_warning: true

# If using Sphinx, optionally build your docs in additional formats such as PDF
formats:
  - pdf
```

Many thanks! :beer:
