### ISSUE TITLE
Docs `build.job` recipe for `poetry` does not work with newer versions

### ISSUE THREAD

**Issue by davidorme** [readthedocs/readthedocs.org#9740]
I'm trying to build a site for a package managed using `poetry` and following the officially documented approach in the `build.jobs` docs [section](https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-poetry). That approach now appears to be failing:

https://readthedocs.org/projects/virtual-rainforest/builds/18663328/

The TLDR on that build log error is that the old `get-poetry.py` install _will not_ install recent versions (`>1.2.0a1`) and that the new `https://install.python-poetry.org` approach _must_ be used instead. I tried using that approach:

```yaml
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  jobs:
    post_create_environment:
      # Install poetry
      - curl -sSL https://install.python-poetry.org | python3 -
      # Tell poetry to not use a virtual environment
      - $HOME/.local/bin/poetry config virtualenvs.create false
      # Install project's dependencies
      - $HOME/.local/bin/poetry install
```

but that doesn't seem to be working: https://readthedocs.org/projects/virtual-rainforest/builds/18663177/

I know that is an apparent error in my package, but it doesn't occur with local `sphinx` builds and seems like a problem with the installed environment? I think @humitos tried this approach and also had problems with the resulting build environment : 

https://github.com/readthedocs/readthedocs.org/pull/9445#issuecomment-1193736700

_Originally posted by @davidorme in https://github.com/readthedocs/readthedocs.org/issues/9445#issuecomment-1318911972_

**Comment by browniebroke** [comment]
I also noticed that the docs were out of date and I tried to update them in https://github.com/readthedocs/readthedocs.org/pull/9743

I think I'm facing the same issue: my package doesn't get installed. From what I can tell, the last line `poetry install` doesn't install the dependecies in the right virtualenv. 

I managed to make my build work with the following solution:

```yaml
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  jobs:
    post_create_environment:
      # Install poetry
      # https://python-poetry.org/docs/#osx--linux--bashonwindows-install-instructions
      - curl -sSL https://install.python-poetry.org | python3 -
      # Tell poetry to not use a virtual environment
      - $HOME/.local/bin/poetry config virtualenvs.create false
    pre_install:
      # Export project dependencies to requirements.txt
      - $HOME/.local/bin/poetry export --with docs > docs/requirements.txt

python:
  install:
    # Install exported dependencies
    - requirements: docs/requirements.txt
    # Install the current package itself
    - method: pip
      path: .
```

Not ideal though.
