### ISSUE TITLE
Compatibility between build.apt_packages and build.commands

### ISSUE THREAD

**Issue by paugier** [readthedocs/readthedocs.org#9772]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/snek5000
* Build URL : https://readthedocs.org/projects/snek5000/builds/18800415/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/paugier

## Expected Result

I'd like to be able to install packages with apt and then uses commands, like this:

```
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  apt_packages:
    - build-essential
    - gfortran
    - libopenmpi-dev
    # - graphviz
  commands:
    - git checkout main
    - git pull --unshallow
    # - apt-get update --assume-yes --quiet
    # - apt-get install --assume-yes --quiet -- build-essential gfortran libopenmpi-dev
    - git clone --depth=1 https://github.com/snek5000/Nek5000_for_snek.git /home/docs/Nek5000
    - ls $NEK_SOURCE_ROOT
    - cat docs/conf.py
    - python -m virtualenv /home/docs/checkouts/readthedocs.org/user_builds/snek5000/envs/latest
    - /home/docs/checkouts/readthedocs.org/user_builds/snek5000/envs/latest/bin/python -m pip install --upgrade --no-cache-dir pip nox
    - /home/docs/checkouts/readthedocs.org/user_builds/snek5000/envs/latest/bin/python -m nox --session docs
    - mkdir _readthedocs
    - mv -r docs/_build/html _readthedocs
```

## Actual Result

When `build.commands` is present, `apt_packages` are not installed.

When I try to run `apt` commands in `build.commands`, I get an error:

```
 apt-get update --assume-yes --quiet
Reading package lists...
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/ 
```
